export const albumSeedArray = [
  // {
  //   id: 'album1',
  //   artist: 'AC/DC',
  //   title: 'Back in Black',
  //   undefined: '',
  // },
  // {
  //   id: 'album2',
  //   artist: 'Alicia Keys',
  //   title: 'Songs in A Minor',
  //   undefined: '',
  // },
  // {
  //   id: 'album3',
  //   artist: 'Amy Winehouse',
  //   title: 'Back to Black',
  //   undefined: '',
  // },
  // {
  //   id: 'album4',
  //   artist: 'Amy Winehouse',
  //   title: 'Frank',
  //   undefined: '',
  // },
  // {
  //   id: 'album5',
  //   artist: 'Aphex Twin',
  //   title: 'Selected Ambient Works 85-92',
  //   undefined: '',
  // },
  // {
  //   id: 'album6',
  //   artist: 'Arcade Fire',
  //   title: 'Funeral',
  //   undefined: '',
  // },
  // {
  //   id: 'album7',
  //   artist: 'Arcade Fire',
  //   title: 'The Suburbs',
  //   undefined: '',
  // },
  // {
  //   id: 'album8',
  //   artist: 'Arctic Monkeys',
  //   title: "Whatever People Say I Am, That's What I'm Not",
  //   undefined: '',
  // },
  // {
  //   id: 'album9',
  //   artist: 'Aretha Franklin',
  //   title: 'I Never Loved a Man the Way I Love You',
  //   undefined: '',
  // },
  // {
  //   id: 'album10',
  //   artist: 'Beastie Boys',
  //   title: 'Check Your Head',
  //   undefined: '',
  // },
  // {
  //   id: 'album11',
  //   artist: 'Beastie Boys',
  //   title: 'Licensed to Ill',
  //   undefined: '',
  // },
  // {
  //   id: 'album12',
  //   artist: 'Beastie Boys',
  //   title: "Paul's Boutique",
  //   undefined: '',
  // },
  // {
  //   id: 'album13',
  //   artist: 'Beastie Boys',
  //   title: 'Ill Communication',
  //   undefined: '',
  // },
  // {
  //   id: 'album14',
  //   artist: 'Beck',
  //   title: 'Odelay',
  //   undefined: '',
  // },
  // {
  //   id: 'album15',
  //   artist: 'Beck',
  //   title: 'Sea Change',
  //   undefined: '',
  // },
  // {
  //   id: 'album16',
  //   artist: 'Beyoncé',
  //   title: 'Beyoncé',
  //   undefined: '',
  // },
  // {
  //   id: 'album17',
  //   artist: 'Beyoncé',
  //   title: 'Lemonade',
  //   undefined: '',
  // },
  // {
  //   id: 'album18',
  //   artist: 'Björk',
  //   title: 'Post',
  //   undefined: '',
  // },
  // {
  //   id: 'album19',
  //   artist: 'Blur',
  //   title: 'Blur',
  //   undefined: '',
  // },
  // {
  //   id: 'album20',
  //   artist: 'Blur',
  //   title: 'Parklife',
  //   undefined: '',
  // },
  // {
  //   id: 'album21',
  //   artist: 'Bob Dylan',
  //   title: 'Blonde on Blonde',
  //   undefined: '',
  // },
  // {
  //   id: 'album22',
  //   artist: 'Bob Dylan',
  //   title: 'Highway 61 Revisited',
  //   undefined: '',
  // },
  // {
  //   id: 'album23',
  //   artist: 'Bob Dylan',
  //   title: 'Time Out of Mind',
  //   undefined: '',
  // },
  // {
  //   id: 'album24',
  //   artist: 'Bob Marley and The Wailers',
  //   title: 'Legend',
  //   undefined: '',
  // },
  // {
  //   id: 'album25',
  //   artist: 'Bon Iver',
  //   title: 'For Emma, Forever Ago',
  //   undefined: '',
  // },
  // {
  //   id: 'album26',
  //   artist: 'Bruce Springsteen',
  //   title: 'Born in the U.S.A.',
  //   undefined: '',
  // },
  // {
  //   id: 'album27',
  //   artist: 'Bruce Springsteen',
  //   title: 'Born to Run',
  //   undefined: '',
  // },
  // {
  //   id: 'album28',
  //   artist: 'Bruce Springsteen',
  //   title: 'Darkness on the Edge of Town',
  //   undefined: '',
  // },
  // {
  //   id: 'album29',
  //   artist: 'Carole King',
  //   title: 'Tapestry',
  //   undefined: '',
  // },
  // {
  //   id: 'album30',
  //   artist: 'Coldplay',
  //   title: 'A Rush of Blood to the Head',
  //   undefined: '',
  // },
  // {
  //   id: 'album31',
  //   artist: 'Daft Punk',
  //   title: 'Discovery',
  //   undefined: '',
  // },
  // {
  //   id: 'album32',
  //   artist: 'Daft Punk',
  //   title: 'Random Access Memories',
  //   undefined: '',
  // },
  // {
  //   id: 'album33',
  //   artist: 'David Bowie',
  //   title: 'Hunky Dory',
  //   undefined: '',
  // },
  // {
  //   id: 'album34',
  //   artist: 'David Bowie',
  //   title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
  //   undefined: '',
  // },
  // {
  //   id: 'album35',
  //   artist: 'David Bowie',
  //   title: 'Blackstar',
  //   undefined: '',
  // },
  // {
  //   id: 'album36',
  //   artist: 'Depeche Mode',
  //   title: 'Violator',
  //   undefined: '',
  // },
  // {
  //   id: 'album37',
  //   artist: 'Dr. Dre',
  //   title: 'The Chronic',
  //   undefined: '',
  // },
  // {
  //   id: 'album38',
  //   artist: 'Elliott Smith',
  //   title: 'Either/Or',
  //   undefined: '',
  // },
  // {
  //   id: 'album39',
  //   artist: 'Elvis Presley',
  //   title: 'Elvis Presley',
  //   undefined: '',
  // },
  // {
  //   id: 'album40',
  //   artist: 'Eminem',
  //   title: 'The Marshall Mathers LP',
  //   undefined: '',
  // },
  // {
  //   id: 'album41',
  //   artist: 'Eminem',
  //   title: 'The Slim Shady LP',
  //   undefined: '',
  // },
  // {
  //   id: 'album42',
  //   artist: 'Fiona Apple',
  //   title: 'The Idler Wheel...',
  //   undefined: '',
  // },
  // {
  //   id: 'album43',
  //   artist: 'Fleet Foxes',
  //   title: 'Fleet Foxes',
  //   undefined: '',
  // },
  // {
  //   id: 'album44',
  //   artist: 'Fleetwood Mac',
  //   title: 'Fleetwood Mac',
  //   undefined: '',
  // },
  // {
  //   id: 'album45',
  //   artist: 'Fleetwood Mac',
  //   title: 'Rumours',
  //   undefined: '',
  // },
  // {
  //   id: 'album46',
  //   artist: 'Fleetwood Mac',
  //   title: 'Tango in the Night',
  //   undefined: '',
  // },
  // {
  //   id: 'album47',
  //   artist: 'Foo Fighters',
  //   title: 'The Colour and the Shape',
  //   undefined: '',
  // },
  // {
  //   id: 'album48',
  //   artist: 'Frank Ocean',
  //   title: 'Channel Orange',
  //   undefined: '',
  // },
  // {
  //   id: 'album49',
  //   artist: 'Frank Sinatra',
  //   title: 'In the Wee Small Hours',
  //   undefined: '',
  // },
  // {
  //   id: 'album50',
  //   artist: 'Gorillaz',
  //   title: 'Demon Days',
  //   undefined: '',
  // },
  // {
  //   id: 'album51',
  //   artist: 'Green Day',
  //   title: 'American Idiot',
  //   undefined: '',
  // },
  // {
  //   id: 'album52',
  //   artist: 'Green Day',
  //   title: 'Dookie',
  //   undefined: '',
  // },
  // {
  //   id: 'album53',
  //   artist: "Guns N' Roses",
  //   title: 'Appetite for Destruction',
  //   undefined: '',
  // },
  // {
  //   id: 'album54',
  //   artist: 'Jay-Z',
  //   title: 'The Blueprint',
  //   undefined: '',
  // },
  // {
  //   id: 'album55',
  //   artist: 'Johnny Cash',
  //   title: 'American IV: The Man Comes Around',
  //   undefined: '',
  // },
  // {
  //   id: 'album56',
  //   artist: 'Johnny Cash',
  //   title: 'At Folsom Prison',
  //   undefined: '',
  // },
  // {
  //   id: 'album57',
  //   artist: 'Johnny Cash',
  //   title: 'Johnny Cash at San Quentin',
  //   undefined: '',
  // },
  // {
  //   id: 'album58',
  //   artist: 'Johnny Cash',
  //   title: 'American Recordings',
  //   undefined: '',
  // },
  // {
  //   id: 'album59',
  //   artist: 'Joni Mitchell',
  //   title: 'Blue',
  //   undefined: '',
  // },
  // {
  //   id: 'album60',
  //   artist: 'Joy Division',
  //   title: 'Unknown Pleasures',
  //   undefined: '',
  // },
  // {
  //   id: 'album61',
  //   artist: 'Kanye West',
  //   title: 'My Beautiful Dark Twisted Fantasy',
  //   undefined: '',
  // },
  // {
  //   id: 'album62',
  //   artist: 'Kendrick Lamar',
  //   title: 'good kid, m.A.A.d city',
  //   undefined: '',
  // },
  // {
  //   id: 'album63',
  //   artist: 'Kendrick Lamar',
  //   title: 'To Pimp a Butterfly',
  //   undefined: '',
  // },
  // {
  //   id: 'album64',
  //   artist: 'Kendrick Lamar',
  //   title: 'DAMN.',
  //   undefined: '',
  // },
  // {
  //   id: 'album65',
  //   artist: 'Lauryn Hill',
  //   title: 'The Miseducation of Lauryn Hill',
  //   undefined: '',
  // },
  // {
  //   id: 'album66',
  //   artist: 'LCD Soundsystem',
  //   title: 'LCD Soundsystem',
  //   undefined: '',
  // },
  // {
  //   id: 'album67',
  //   artist: 'LCD Soundsystem',
  //   title: 'Sound of Silver',
  //   undefined: '',
  // },
  // {
  //   id: 'album68',
  //   artist: 'Led Zeppelin',
  //   title: 'Led Zeppelin II',
  //   undefined: '',
  // },
  // {
  //   id: 'album69',
  //   artist: 'Led Zeppelin',
  //   title: 'Led Zeppelin IV',
  //   undefined: '',
  // },
  // {
  //   id: 'album70',
  //   artist: 'Led Zeppelin',
  //   title: 'Physical Graffiti',
  //   undefined: '',
  // },
  // {
  //   id: 'album71',
  //   artist: 'Madonna',
  //   title: 'Ray of Light',
  //   undefined: '',
  // },
  // {
  //   id: 'album72',
  //   artist: 'Marvin Gaye',
  //   title: "What's Going On",
  //   undefined: '',
  // },
  // {
  //   id: 'album73',
  //   artist: 'Massive Attack',
  //   title: 'Mezzanine',
  //   undefined: '',
  // },
  // {
  //   id: 'album74',
  //   artist: 'Metallica',
  //   title: 'Metallica (The Black Album)',
  //   undefined: '',
  // },
  // {
  //   id: 'album75',
  //   artist: 'Metallica',
  //   title: 'Master of Puppets',
  //   undefined: '',
  // },
  // {
  //   id: 'album77',
  //   artist: 'Michael Jackson',
  //   title: 'Off the Wall',
  //   undefined: '',
  // },
  // {
  //   id: 'album78',
  //   artist: 'Michael Jackson',
  //   title: 'Thriller',
  //   undefined: '',
  // },
  // {
  //   id: 'album79',
  //   artist: 'Michael Jackson',
  //   title: 'Dangerous',
  //   undefined: '',
  // },
  // {
  //   id: 'album80',
  //   artist: 'Miles Davis',
  //   title: 'Bitches Brew',
  //   undefined: '',
  // },
  // {
  //   id: 'album81',
  //   artist: 'Miles Davis',
  //   title: 'Kind of Blue',
  //   undefined: '',
  // },
  // {
  //   id: 'album82',
  //   artist: 'My Bloody Valentine',
  //   title: 'Loveless',
  //   undefined: '',
  // },
  // {
  //   id: 'album83',
  //   artist: 'Nas',
  //   title: 'Illmatic',
  //   undefined: '',
  // },
  // {
  //   id: 'album84',
  //   artist: 'Neil Young',
  //   title: 'After the Gold Rush',
  //   undefined: '',
  // },
  // {
  //   id: 'album85',
  //   artist: 'Neil Young',
  //   title: 'Harvest',
  //   undefined: '',
  // },
  // {
  //   id: 'album86',
  //   artist: 'Neil Young',
  //   title: 'Harvest Moon',
  //   undefined: '',
  // },
  // {
  //   id: 'album87',
  //   artist: 'Nick Cave & The Bad Seeds',
  //   title: 'Let Love In',
  //   undefined: '',
  // },
  // {
  //   id: 'album88',
  //   artist: 'Nine Inch Nails',
  //   title: 'The Downward Spiral',
  //   undefined: '',
  // },
  // {
  //   id: 'album89',
  //   artist: 'Nirvana',
  //   title: 'Nevermind',
  //   undefined: '',
  // },
  // {
  //   id: 'album90',
  //   artist: 'Nirvana',
  //   title: 'In Utero',
  //   undefined: '',
  // },
  // {
  //   id: 'album91',
  //   artist: 'Oasis',
  //   title: "(What's the Story) Morning Glory?",
  //   undefined: '',
  // },
  // {
  //   id: 'album92',
  //   artist: 'Oasis',
  //   title: 'Be Here Now',
  //   undefined: '',
  // },
  // {
  //   id: 'album93',
  //   artist: 'Oasis',
  //   title: 'Definitely Maybe',
  //   undefined: '',
  // },
  // {
  //   id: 'album94',
  //   artist: 'OutKast',
  //   title: 'Aquemini',
  //   undefined: '',
  // },
  // {
  //   id: 'album95',
  //   artist: 'Patti Smith',
  //   title: 'Horses',
  //   undefined: '',
  // },
  // {
  //   id: 'album96',
  //   artist: 'Patti Smith Group',
  //   title: 'Easter',
  //   undefined: '',
  // },
  // {
  //   id: 'album97',
  //   artist: 'Paul Simon',
  //   title: 'Graceland',
  //   undefined: '',
  // },
  // {
  //   id: 'album98',
  //   artist: 'Pearl Jam',
  //   title: 'Ten',
  //   undefined: '',
  // },
  // {
  //   id: 'album99',
  //   artist: 'Pink Floyd',
  //   title: 'The Dark Side of the Moon',
  //   undefined: '',
  // },
  // {
  //   id: 'album100',
  //   artist: 'Pink Floyd',
  //   title: 'The Wall',
  //   undefined: '',
  // },
  // {
  //   id: 'album101',
  //   artist: 'Pink Floyd',
  //   title: 'Wish You Were Here',
  //   undefined: '',
  // },
  // {
  //   id: 'album102',
  //   artist: 'PJ Harvey',
  //   title: 'Rid of Me',
  //   undefined: '',
  // },
  // {
  //   id: 'album103',
  //   artist: 'PJ Harvey',
  //   title: 'Dry',
  //   undefined: '',
  // },
  // {
  //   id: 'album104',
  //   artist: 'PJ Harvey',
  //   title: 'Let England Shake',
  //   undefined: '',
  // },
  // {
  //   id: 'album105',
  //   artist: 'PJ Harvey',
  //   title: 'Stories from the City, Stories from the Sea',
  //   undefined: '',
  // },
  // {
  //   id: 'album106',
  //   artist: 'Portishead',
  //   title: 'Dummy',
  //   undefined: '',
  // },
  // {
  //   id: 'album107',
  //   artist: 'Prince',
  //   title: '1999',
  //   undefined: '',
  // },
  // {
  //   id: 'album108',
  //   artist: 'Prince',
  //   title: "Sign o' the Times",
  //   undefined: '',
  // },
  // {
  //   id: 'album109',
  //   artist: 'Prince and The Revolution',
  //   title: 'Purple Rain',
  //   undefined: '',
  // },
  // {
  //   id: 'album110',
  //   artist: 'Public Enemy',
  //   title: 'It Takes a Nation of Millions to Hold Us Back',
  //   undefined: '',
  // },
  // {
  //   id: 'album111',
  //   artist: 'Queen',
  //   title: 'A Night at the Opera',
  //   undefined: '',
  // },
  // {
  //   id: 'album112',
  //   artist: 'Queen',
  //   title: 'News of the World',
  //   undefined: '',
  // },
  // {
  //   id: 'album113',
  //   artist: 'Queens of the Stone Age',
  //   title: 'Rated R',
  //   undefined: '',
  // },
  // {
  //   id: 'album114',
  //   artist: 'Queens of the Stone Age',
  //   title: 'Songs for the Deaf',
  //   undefined: '',
  // },
  // {
  //   id: 'album115',
  //   artist: 'R.E.M.',
  //   title: 'Automatic for the People',
  //   undefined: '',
  // },
  // {
  //   id: 'album116',
  //   artist: 'R.E.M.',
  //   title: 'Out of Time',
  //   undefined: '',
  // },
  // {
  //   id: 'album117',
  //   artist: 'Radiohead',
  //   title: 'Amnesiac',
  //   undefined: '',
  // },
  // {
  //   id: 'album118',
  //   artist: 'Radiohead',
  //   title: 'Kid A',
  //   undefined: '',
  // },
  // {
  //   id: 'album119',
  //   artist: 'Radiohead',
  //   title: 'OK Computer',
  //   undefined: '',
  // },
  // {
  //   id: 'album120',
  //   artist: 'Radiohead',
  //   title: 'The Bends',
  //   undefined: '',
  // },
  // {
  //   id: 'album121',
  //   artist: 'Radiohead',
  //   title: 'In Rainbows',
  //   undefined: '',
  // },
  // {
  //   id: 'album122',
  //   artist: 'Rage Against the Machine',
  //   title: 'Rage Against the Machine',
  //   undefined: '',
  // },
  // {
  //   id: 'album123',
  //   artist: 'Red Hot Chili Peppers',
  //   title: 'Californication',
  //   undefined: '',
  // },
  // {
  //   id: 'album124',
  //   artist: 'Sigur Rós',
  //   title: 'Ágætis byrjun',
  //   undefined: '',
  // },
  // {
  //   id: 'album125',
  //   artist: 'Simon & Garfunkel',
  //   title: 'Bridge over Troubled Water',
  //   undefined: '',
  // },
  // {
  //   id: 'album126',
  //   artist: 'Smashing Pumpkins',
  //   title: 'Siamese Dream',
  //   undefined: '',
  // },
  // {
  //   id: 'album127',
  //   artist: 'Snoop Dogg',
  //   title: 'Doggystyle',
  //   undefined: '',
  // },
  // {
  //   id: 'album128',
  //   artist: 'St. Vincent',
  //   title: 'St. Vincent',
  //   undefined: '',
  // },
  // {
  //   id: 'album129',
  //   artist: 'Stevie Wonder',
  //   title: 'Innervisions',
  //   undefined: '',
  // },
  // {
  //   id: 'album130',
  //   artist: 'Stevie Wonder',
  //   title: 'Songs in the Key of Life',
  //   undefined: '',
  // },
  // {
  //   id: 'album131',
  //   artist: 'Sufjan Stevens',
  //   title: 'Illinois',
  //   undefined: '',
  // },
  // {
  //   id: 'album132',
  //   artist: 'Talking Heads',
  //   title: 'Remain in Light',
  //   undefined: '',
  // },
  // {
  //   id: 'album133',
  //   artist: 'The Beach Boys',
  //   title: 'Pet Sounds',
  //   undefined: '',
  // },
  // {
  //   id: 'album134',
  //   artist: 'The Beatles',
  //   title: 'Abbey Road',
  //   undefined: '',
  // },
  // {
  //   id: 'album135',
  //   artist: 'The Beatles',
  //   title: 'Help!',
  //   undefined: '',
  // },
  // {
  //   id: 'album136',
  //   artist: 'The Beatles',
  //   title: 'Revolver',
  //   undefined: '',
  // },
  // {
  //   id: 'album137',
  //   artist: 'The Beatles',
  //   title: 'Rubber Soul',
  //   undefined: '',
  // },
  // {
  //   id: 'album138',
  //   artist: 'The Beatles',
  //   title: "Sgt. Pepper's Lonely Hearts Club Band",
  //   undefined: '',
  // },
  // {
  //   id: 'album139',
  //   artist: 'The Beatles',
  //   title: 'The Beatles (The White Album)',
  //   undefined: '',
  // },
  // {
  //   id: 'album140',
  //   artist: 'The Black Keys',
  //   title: 'Brothers',
  //   undefined: '',
  // },
  // {
  //   id: 'album141',
  //   artist: 'The Clash',
  //   title: 'London Calling',
  //   undefined: '',
  // },
  // {
  //   id: 'album142',
  //   artist: 'The Clash',
  //   title: 'The Clash',
  //   undefined: '',
  // },
  // {
  //   id: 'album143',
  //   artist: 'The Cure',
  //   title: 'Disintegration',
  //   undefined: '',
  // },
  // {
  //   id: 'album144',
  //   artist: 'The Doors',
  //   title: 'The Doors',
  //   undefined: '',
  // },
  // {
  //   id: 'album145',
  //   artist: 'Eagles',
  //   title: 'Hotel California',
  //   undefined: '',
  // },
  // {
  //   id: 'album146',
  //   artist: 'The Flaming Lips',
  //   title: 'The Soft Bulletin',
  //   undefined: '',
  // },
  // {
  //   id: 'album147',
  //   artist: 'Fugees',
  //   title: 'The Score',
  //   undefined: '',
  // },
  // {
  //   id: 'album148',
  //   artist: 'The Jimi Hendrix Experience',
  //   title: 'Are You Experienced',
  //   undefined: '',
  // },
  // {
  //   id: 'album149',
  //   artist: 'The Killers',
  //   title: 'Hot Fuss',
  //   undefined: '',
  // },
  // {
  //   id: 'album150',
  //   artist: 'The National',
  //   title: 'High Violet',
  //   undefined: '',
  // },
  // {
  //   id: 'album151',
  //   artist: 'Notorious B.I.G.',
  //   title: 'Ready to Die',
  //   undefined: '',
  // },
  // {
  //   id: 'album152',
  //   artist: 'Notorious B.I.G.',
  //   title: 'Life After Death',
  //   undefined: '',
  // },
  // {
  //   id: 'album153',
  //   artist: 'The Prodigy',
  //   title: 'The Fat of the Land',
  //   undefined: '',
  // },
  // {
  //   id: 'album154',
  //   artist: 'The Rolling Stones',
  //   title: 'Beggars Banquet',
  //   undefined: '',
  // },
  // {
  //   id: 'album155',
  //   artist: 'The Rolling Stones',
  //   title: 'Exile on Main St.',
  //   undefined: '',
  // },
  // {
  //   id: 'album156',
  //   artist: 'The Rolling Stones',
  //   title: 'Let It Bleed',
  //   undefined: '',
  // },
  // {
  //   id: 'album157',
  //   artist: 'The Rolling Stones',
  //   title: 'Sticky Fingers',
  //   undefined: '',
  // },
  // {
  //   id: 'album158',
  //   artist: 'The Roots',
  //   title: 'Things Fall Apart',
  //   undefined: '',
  // },
  // {
  //   id: 'album159',
  //   artist: 'The Smashing Pumpkins',
  //   title: 'Mellon Collie and the Infinite Sadness',
  //   undefined: '',
  // },
  // {
  //   id: 'album160',
  //   artist: 'The Smiths',
  //   title: 'Meat Is Murder',
  //   undefined: '',
  // },
  // {
  //   id: 'album161',
  //   artist: 'The Smiths',
  //   title: 'The Queen Is Dead',
  //   undefined: '',
  // },
  // {
  //   id: 'album162',
  //   artist: 'The Strokes',
  //   title: 'Is This It',
  //   undefined: '',
  // },
  // {
  //   id: 'album163',
  //   artist: 'The Velvet Underground',
  //   title: 'Loaded',
  //   undefined: '',
  // },
  // {
  //   id: 'album164',
  //   artist: 'The Velvet Underground',
  //   title: 'The Velvet Underground & Nico',
  //   undefined: '',
  // },
  // {
  //   id: 'album165',
  //   artist: 'The White Stripes',
  //   title: 'Elephant',
  //   undefined: '',
  // },
  // {
  //   id: 'album166',
  //   artist: 'The White Stripes',
  //   title: 'White Blood Cells',
  //   undefined: '',
  // },
  // {
  //   id: 'album167',
  //   artist: 'The Who',
  //   title: 'Tommy',
  //   undefined: '',
  // },
  // {
  //   id: 'album168',
  //   artist: 'The Who',
  //   title: "Who's Next",
  //   undefined: '',
  // },
  // {
  //   id: 'album169',
  //   artist: 'The xx',
  //   title: 'xx',
  //   undefined: '',
  // },
  // {
  //   id: 'album170',
  //   artist: 'Tool',
  //   title: 'Undertow',
  //   undefined: '',
  // },
  // {
  //   id: 'album171',
  //   artist: 'U2',
  //   title: 'The Joshua Tree',
  //   undefined: '',
  // },
  // {
  //   id: 'album172',
  //   artist: 'U2',
  //   title: 'Achtung Baby',
  //   undefined: '',
  // },
  // {
  //   id: 'album173',
  //   artist: 'Vampire Weekend',
  //   title: 'Modern Vampires of the City',
  //   undefined: '',
  // },
  // {
  //   id: 'album174',
  //   artist: 'Van Morrison',
  //   title: 'Moondance',
  //   undefined: '',
  // },
  // {
  //   id: 'album175',
  //   artist: 'Weezer',
  //   title: 'Weezer',
  //   undefined: '',
  // },
  // {
  //   id: 'album177',
  //   artist: 'Wilco',
  //   title: 'Yankee Hotel Foxtrot',
  //   undefined: '',
  // },
  // {
  //   id: 'album178',
  //   artist: 'John Coltrane',
  //   title: 'A Love Supreme',
  //   undefined: '',
  // },
  // {
  //   id: 'album179',
  //   artist: 'Dave Brubeck Quartet',
  //   title: 'Time Out',
  //   undefined: '',
  // },
  // {
  //   id: 'album180',
  //   artist: 'John Coltrane',
  //   title: 'Blue Train',
  //   undefined: '',
  // },
  // {
  //   id: 'album181',
  //   artist: 'Charles Mingus',
  //   title: 'Mingus Ah Um',
  //   undefined: '',
  // },
  // {
  //   id: 'album182',
  //   artist: 'John Coltrane',
  //   title: 'Giant Steps',
  //   undefined: '',
  // },
  // {
  //   id: 'album183',
  //   artist: 'Ornette Coleman',
  //   title: 'The Shape of Jazz to Come',
  //   undefined: '',
  // },
  // {
  //   id: 'album184',
  //   artist: 'Ella Fitzgerald',
  //   title: 'Ella Fitzgerald Sings the Cole Porter Songbook',
  //   undefined: '',
  // },
  // {
  //   id: 'album185',
  //   artist: 'Charles Mingus',
  //   title: 'The Black Saint and the Sinner Lady',
  //   undefined: '',
  // },
  // {
  //   id: 'album186',
  //   artist: 'Herbie Hancock',
  //   title: 'Head Hunters',
  //   undefined: '',
  // },
  // {
  //   id: 'album188',
  //   artist: 'Miles Davis',
  //   title: 'Birth of the Cool',
  //   undefined: '',
  // },
  // {
  //   id: 'album189',
  //   artist: 'The Dave Brubeck Quartet',
  //   title: 'Take Five',
  //   undefined: '',
  // },
  // {
  //   id: 'album190',
  //   artist: 'John Coltrane',
  //   title: 'My Favorite Things',
  //   undefined: '',
  // },
  // {
  //   id: 'album191',
  //   artist: 'Art Blakey and the Jazz Messengers',
  //   title: 'A Night in Tunisia',
  //   undefined: '',
  // },
  // {
  //   id: 'album192',
  //   artist: 'Keith Jarrett',
  //   title: 'The Köln Concert',
  //   undefined: '',
  // },
  // {
  //   id: 'album193',
  //   artist: 'Herbie Hancock',
  //   title: 'Maiden Voyage',
  //   undefined: '',
  // },
  // {
  //   id: 'album194',
  //   artist: 'Ella Fitzgerald',
  //   title: 'The Complete Ella Fitzgerald Song Books',
  //   undefined: '',
  // },
  // {
  //   id: 'album195',
  //   artist: 'Sonny Rollins',
  //   title: 'Saxophone Colossus',
  //   undefined: '',
  // },
  // {
  //   id: 'album196',
  //   artist: 'Eric Dolphy',
  //   title: 'Out to Lunch!',
  //   undefined: '',
  // },
  // {
  //   id: 'album197',
  //   artist: 'Chick Corea',
  //   title: 'Now He Sings, Now He Sobs',
  //   undefined: '',
  // },
  // {
  //   id: 'album198',
  //   artist: 'Art Blakey and the Jazz Messengers',
  //   title: "Moanin'",
  //   undefined: '',
  // },
  // {
  //   id: 'album199',
  //   artist: 'Ramones',
  //   title: 'Ramones',
  //   undefined: '',
  // },
  // {
  //   id: 'album200',
  //   artist: 'Sex Pistols',
  //   title: "Never Mind the Bollocks, Here's the Sex Pistols",
  //   undefined: '',
  // },
  // {
  //   id: 'album201',
  //   artist: 'The Stooges',
  //   title: 'Raw Power',
  //   undefined: '',
  // },
  // {
  //   id: 'album202',
  //   artist: 'Misfits',
  //   title: 'Walk Among Us',
  //   undefined: '',
  // },
  // {
  //   id: 'album203',
  //   artist: 'Bad Brains',
  //   title: 'Bad Brains',
  //   undefined: '',
  // },
  // {
  //   id: 'album204',
  //   artist: 'Black Flag',
  //   title: 'Damaged',
  //   undefined: '',
  // },
  // {
  //   id: 'album205',
  //   artist: 'The Damned',
  //   title: 'Damned Damned Damned',
  //   undefined: '',
  // },
  // {
  //   id: 'album206',
  //   artist: 'Dead Kennedys',
  //   title: 'Fresh Fruit for Rotting Vegetables',
  //   undefined: '',
  // },
  // {
  //   id: 'album207',
  //   artist: 'Descendents',
  //   title: 'Milo Goes to College',
  //   undefined: '',
  // },
  // {
  //   id: 'album208',
  //   artist: 'The Offspring',
  //   title: 'Smash',
  //   undefined: '',
  // },
  // {
  //   id: 'album209',
  //   artist: 'Rancid',
  //   title: '...And Out Come the Wolves',
  //   undefined: '',
  // },
  // {
  //   id: 'album210',
  //   artist: 'Minor Threat',
  //   title: 'Minor Threat',
  //   undefined: '',
  // },
  // {
  //   id: 'album211',
  //   artist: 'Social Distortion',
  //   title: 'Social Distortion',
  //   undefined: '',
  // },
  // {
  //   id: 'album212',
  //   artist: 'Operation Ivy',
  //   title: 'Energy',
  //   undefined: '',
  // },
  // {
  //   id: 'album213',
  //   artist: 'Buzzcocks',
  //   title: 'Love Bites',
  //   undefined: '',
  // },
  // {
  //   id: 'album214',
  //   artist: 'X',
  //   title: 'Los Angeles',
  //   undefined: '',
  // },
  // {
  //   id: 'album215',
  //   artist: 'Germs',
  //   title: '(GI)',
  //   undefined: '',
  // },
  // {
  //   id: 'album216',
  //   artist: 'Fugazi',
  //   title: 'Repeater',
  //   undefined: '',
  // },
  // {
  //   id: 'album217',
  //   artist: 'The Replacements',
  //   title: 'Let It Be',
  //   undefined: '',
  // },
  // {
  //   id: 'album218',
  //   artist: 'The Dead Boys',
  //   title: 'Young, Loud and Snotty',
  //   undefined: '',
  // },
  // {
  //   id: 'album219',
  //   artist: 'Bad Religion',
  //   title: 'Suffer',
  //   undefined: '',
  // },
  // {
  //   id: 'album220',
  //   artist: 'Hüsker Dü',
  //   title: 'Zen Arcade',
  //   undefined: '',
  // },
  // {
  //   id: 'album221',
  //   artist: 'The Exploited',
  //   title: 'Punks Not Dead',
  //   undefined: '',
  // },
  // {
  //   id: 'album222',
  //   artist: 'Kraftwerk',
  //   title: 'Autobahn',
  //   undefined: '',
  // },
  // {
  //   id: 'album227',
  //   artist: 'Massive Attack',
  //   title: 'Blue Lines',
  //   undefined: '',
  // },
  // {
  //   id: 'album228',
  //   artist: 'The Chemical Brothers',
  //   title: 'Dig Your Own Hole',
  //   undefined: '',
  // },
  // {
  //   id: 'album229',
  //   artist: 'Moby',
  //   title: 'Play',
  //   undefined: '',
  // },
  // {
  //   id: 'album231',
  //   artist: 'Justice',
  //   title: 'Cross',
  //   undefined: '',
  // },
  // {
  //   id: 'album232',
  //   artist: 'Burial',
  //   title: 'Untrue',
  //   undefined: '',
  // },
  // {
  //   id: 'album233',
  //   artist: 'The Knife',
  //   title: 'Silent Shout',
  //   undefined: '',
  // },
  // {
  //   id: 'album234',
  //   artist: 'Boards of Canada',
  //   title: 'Music Has the Right to Children',
  //   undefined: '',
  // },
  // {
  //   id: 'album235',
  //   artist: 'Jean-Michel Jarre',
  //   title: 'Oxygène',
  //   undefined: '',
  // },
  // {
  //   id: 'album236',
  //   artist: 'New Order',
  //   title: 'Brotherhood',
  //   undefined: '',
  // },
  // {
  //   id: 'album237',
  //   artist: 'The Prodigy',
  //   title: 'Music for the Jilted Generation',
  //   undefined: '',
  // },
  // {
  //   id: 'album238',
  //   artist: 'Goldie',
  //   title: 'Timeless',
  //   undefined: '',
  // },
  // {
  //   id: 'album239',
  //   artist: 'The Chemical Brothers',
  //   title: 'Exit Planet Dust',
  //   undefined: '',
  // },
  // {
  //   id: 'album240',
  //   artist: 'Air',
  //   title: 'Moon Safari',
  //   undefined: '',
  // },
  {
    id: 'album241',
    artist: 'Kraftwerk',
    title: 'Trans-Europe Express',
    undefined: '',
  },
  {
    id: 'album242',
    artist: 'Giorgio Moroder',
    title: 'From Here to Eternity',
    undefined: '',
  },
  {
    id: 'album243',
    artist: 'Four Tet',
    title: 'Rounds',
    undefined: '',
  },
  {
    id: 'album244',
    artist: 'Pet Shop Boys',
    title: 'West End Girls',
    undefined: '',
  },
  {
    id: 'album245',
    artist: 'Aphex Twin',
    title: 'Richard D. James Album',
    undefined: '',
  },
  {
    id: 'album246',
    artist: 'Moderat',
    title: 'Moderat',
    undefined: '',
  },
  {
    id: 'album247',
    artist: 'Jamie xx',
    title: 'In Colour',
    undefined: '',
  },
  {
    id: 'album248',
    artist: 'Bonobo',
    title: 'Black Sands',
    undefined: '',
  },
  {
    id: 'album249',
    artist: 'Four Year Strong',
    title: 'Enemy of the World',
    undefined: '',
  },
];
