export const crateSeedArray = [
  {
    id: 'crate1',
    title: 'Best of the Decade',
    description: 'Energetic beats to get your heart pumping and feet moving.',
    creatorid: 'profile15',
    favoritedby: '',
    labels: 'label2,label84,label6',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate2',
    title: 'Melancholic Mornings',
    description: 'Soothing melodies for relaxation and unwinding after a long day.',
    creatorid: 'profile58',
    favoritedby: '',
    labels: 'label71,label116,label70,label99',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate3',
    title: 'Pumped Up Anthems',
    description: 'Upbeat and catchy tunes to brighten your mood and lift your spirits.',
    creatorid: 'profile57',
    favoritedby: 'profile80,profile77,profile21',
    labels: 'label128,label50',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate4',
    title: 'Indie Delights',
    description: 'Soulful ballads that touch the depths of your emotions.',
    creatorid: 'profile29',
    favoritedby: 'profile12',
    labels: 'label127,label40',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate5',
    title: 'Throwback Jams',
    description: 'Feel-good anthems that will have you singing along at the top of your lungs.',
    creatorid: 'profile78',
    favoritedby: '',
    labels: 'label111,label188,label43',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate6',
    title: 'Chill Vibes Only',
    description: 'Atmospheric tracks that transport you to another world.',
    creatorid: 'profile18',
    favoritedby: 'profile51,profile59',
    labels: 'label75',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate7',
    title: 'Ultimate Road Trip Hits',
    description: 'Epic orchestral compositions that evoke a sense of grandeur and adventure.',
    creatorid: 'profile64',
    favoritedby: 'profile1,profile85',
    labels: 'label20,label132,label156,label86,label35',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate8',
    title: 'Electro Pop Bangers',
    description: 'Nostalgic hits that take you back to a different era.',
    creatorid: 'profile9',
    favoritedby: 'profile65',
    labels: 'label40',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate9',
    title: 'Soulful Serenade',
    description: 'Laid-back acoustic vibes for those lazy Sunday mornings.',
    creatorid: 'profile10',
    favoritedby: 'profile43,profile34',
    labels: 'label153,label155,label20,label161,label177,label173',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate10',
    title: 'Fresh Discoveries',
    description: 'Dancefloor bangers that will make you move and groove all night long.',
    creatorid: 'profile1',
    favoritedby: '',
    labels: 'label111,label156',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate11',
    title: 'Rock Classics Rewind',
    description: 'Soul-stirring love songs that tug at your heartstrings.',
    creatorid: 'profile38',
    favoritedby: 'profile1',
    labels: 'label190,label3,label34,label50',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate12',
    title: 'EDM Explosion',
    description: 'Inspirational tracks to motivate and empower you.',
    creatorid: 'profile4',
    favoritedby: 'profile18,profile16,profile29',
    labels: 'label13,label21,label121,label199',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate13',
    title: 'Smooth Jazz Retreat',
    description: 'Mind-bending electronic sounds that push the boundaries of music.',
    creatorid: 'profile58',
    favoritedby: 'profile54,profile31',
    labels: 'label202,label179,label169,label127,label174,label102,label73',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate14',
    title: 'Rap Royalty',
    description: 'Heartfelt folk tunes that tell stories of life and love.',
    creatorid: 'profile38',
    favoritedby: '',
    labels: 'label95,label151,label192,label88,label116',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate15',
    title: 'Acoustic Affair',
    description: 'Uplifting gospel music that fills your spirit with joy and hope.',
    creatorid: 'profile60',
    favoritedby: '',
    labels: 'label181,label155',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate16',
    title: 'Dance Party Anthems',
    description: 'Intense rock anthems that make you want to unleash your inner rebel.',
    creatorid: 'profile42',
    favoritedby: '',
    labels: 'label92,label53,label111,label43,label135,label15,label176',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate17',
    title: 'Golden Oldies',
    description: 'Quirky and eclectic tracks that defy genre boundaries.',
    creatorid: 'profile65',
    favoritedby: 'profile67,profile50,profile83',
    labels: 'label152,label101,label77,label177',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate18',
    title: 'Alternative Rock Riot',
    description: 'Mellow jazz tunes perfect for a cozy evening with a glass of wine.',
    creatorid: 'profile3',
    favoritedby: 'profile47,profile49',
    labels: 'label140,label200,label35,label144,label173,label37',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate19',
    title: 'Country Roads Collection',
    description: 'Powerful rap verses that speak truth and challenge the status quo.',
    creatorid: 'profile11',
    favoritedby: 'profile73,profile23,profile8,profile83',
    labels: 'label15,label8,label177',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate20',
    title: 'Rhythm & Blues Revival',
    description: 'Dreamy indie pop melodies that create an atmosphere of bliss.',
    creatorid: 'profile38',
    favoritedby: '',
    labels: 'label42,label140,label33,label98',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate21',
    title: 'Workout Warriors',
    description: 'Melancholic songs that capture the beauty of sadness and longing.',
    creatorid: 'profile16',
    favoritedby: 'profile71',
    labels: 'label158,label10',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate22',
    title: 'Songs for Rainy Days',
    description: 'Sensual R&B tracks that set the mood for a romantic evening.',
    creatorid: 'profile80',
    favoritedby: 'profile27,profile42',
    labels: 'label11,label163,label152,label125',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate23',
    title: 'Reggae Rhythms',
    description: 'Captivating classical compositions that stir your soul.',
    creatorid: 'profile49',
    favoritedby: 'profile16,profile76',
    labels: 'label92,label190',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate24',
    title: '90s Nostalgia',
    description: 'Reggae rhythms that bring the warmth of the Caribbean to your ears.',
    creatorid: 'profile42',
    favoritedby: 'profile89',
    labels: 'label21,label197,label167',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate25',
    title: 'Summer Grooves',
    description: 'Dynamic instrumental tracks that ignite your imagination.',
    creatorid: 'profile14',
    favoritedby: 'profile16',
    labels: 'label11,label156,label82,label116',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate26',
    title: 'Road Trip Mixtape',
    description: 'Up-and-coming artists showcasing their raw talent and unique sound.',
    creatorid: 'profile86',
    favoritedby: '',
    labels: 'label191,label58,label10,label151',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate27',
    title: 'Latin Fever',
    description: 'Epic movie soundtracks that transport you into cinematic worlds.',
    creatorid: 'profile6',
    favoritedby: 'profile14',
    labels: 'label22,label98,label180',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate28',
    title: 'Relaxing Instrumentals',
    description: 'Up-tempo country hits that make you want to put on your cowboy boots.',
    creatorid: 'profile84',
    favoritedby: 'profile45,profile52',
    labels: 'label131,label52',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate29',
    title: 'Feel-Good Favorites',
    description: 'Experimental sounds that challenge traditional notions of music.',
    creatorid: 'profile37',
    favoritedby: '',
    labels: 'label104,label103,label167,label198',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate30',
    title: 'Electronic Escapade',
    description: 'Chill electronic beats perfect for a laid-back evening with friends.',
    creatorid: 'profile3',
    favoritedby: 'profile52',
    labels: 'label104,label167,label194',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate31',
    title: 'Rock Ballad Bliss',
    description: 'Anthems of resilience and strength to help you overcome obstacles.',
    creatorid: 'profile4',
    favoritedby: 'profile4,profile19',
    labels: 'label17',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate32',
    title: 'Soul Sisters',
    description: 'Indie rock anthems for the rebels and dreamers.',
    creatorid: 'profile63',
    favoritedby: 'profile54,profile3',
    labels: 'label46,label117,label107,label64',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate33',
    title: 'Hip Hop Hits',
    description: 'Melodic metal tracks that blend aggression with intricate harmonies.',
    creatorid: 'profile23',
    favoritedby: 'profile76,profile3',
    labels: 'label152,label181,label54',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate34',
    title: 'Folk & Acoustic Melodies',
    description: 'Inspirational gospel hymns that uplift and inspire.',
    creatorid: 'profile63',
    favoritedby: 'profile61,profile80,profile3',
    labels: 'label1,label139,label136,label119',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate35',
    title: 'Pop Party Starters',
    description: 'Bittersweet songs that capture the complexities of human emotions.',
    creatorid: 'profile23',
    favoritedby: 'profile23,profile31,profile3',
    labels: 'label152,label135',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate36',
    title: 'Jazz Lounge',
    description: 'Catchy pop hits that will have you singing along from the first note.',
    creatorid: 'profile61',
    favoritedby: 'profile7,profile3',
    labels: 'label2,label20',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate37',
    title: 'Indie Folk Frenzy',
    description: 'Soulful blues melodies that speak directly to your heart.',
    creatorid: 'profile76',
    favoritedby: 'profile5,profile3',
    labels: 'label125,label140,label114',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate38',
    title: 'Motivational Anthems',
    description: 'Rhythmic hip-hop tracks that make you nod your head to the beat.',
    creatorid: 'profile76',
    favoritedby: 'profile69,profile3',
    labels: 'label200,label14,label64',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate39',
    title: 'Vintage Vinyl',
    description: 'Atmospheric post-rock compositions that build and swell with emotion.',
    creatorid: 'profile44',
    favoritedby: 'profile17,profile91,profile3',
    labels: 'label128,label69,label124,label115',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate40',
    title: 'Tropical Beats',
    description: 'Emotional piano ballads that tug at your heartstrings.',
    creatorid: 'profile22',
    favoritedby: 'profile19,profile3',
    labels: 'label102,label195,label28,label168,label155,label112',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate41',
    title: 'Urban Legends',
    description: 'Infectious world music rhythms that make you want to dance.',
    creatorid: 'profile12',
    favoritedby: 'profile3',
    labels: 'label28,label87',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate42',
    title: 'Coffeehouse Chill',
    description: "Raw and honest singer-songwriter tracks that lay bare the artist's soul.",
    creatorid: 'profile83',
    favoritedby: 'profile82,profile68,profile3',
    labels: 'label62,label44,label3,label106,label43',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate43',
    title: 'Guitar Gods',
    description: 'Groovy funk tunes that get your body moving and your hips shaking.',
    creatorid: 'profile8',
    favoritedby: 'profile3',
    labels: 'label167,label147',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate44',
    title: 'Classic Disco Hits',
    description: 'Ambient electronic sounds that create a serene and introspective atmosphere.',
    creatorid: 'profile22',
    favoritedby: 'profile1,profile3',
    labels: 'label189,label1,label114,label21,label13,label12,label89,label161',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate45',
    title: 'Inspirational Soundscapes',
    description: 'Enchanting Celtic melodies that transport you to mystical lands.',
    creatorid: 'profile75',
    favoritedby: 'profile55,profile70,profile3',
    labels: 'label110,label57,label80,label132',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate46',
    title: 'R&B Slow Jams',
    description: 'Thought-provoking alternative tracks that challenge societal norms.',
    creatorid: 'profile34',
    favoritedby: 'profile78,profile3',
    labels: 'label169,label201,label54,label3,label193,label159,label163',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate47',
    title: 'Epic Film Scores',
    description: 'Emotional orchestral arrangements that bring tears to your eyes.',
    creatorid: 'profile65',
    favoritedby: 'profile3',
    labels: 'label155,label128,label25,label149',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate48',
    title: 'High-Energy Workout Mix',
    description: 'Joyful and lively folk songs that make you want to join in on the chorus.',
    creatorid: 'profile4',
    favoritedby: 'profile13,profile3',
    labels: 'label170,label115',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate49',
    title: 'Retro Rewind',
    description: 'Mind-bending progressive rock tracks that take you on a musical journey.',
    creatorid: 'profile33',
    favoritedby: 'profile3',
    labels: 'label199,label169,label13,label59,label41,label135,label30,label160,label33,label131,label183',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate50',
    title: 'Psychedelic Soiree',
    description: 'Lush and dreamy shoegaze sounds that envelop you in a sonic haze.',
    creatorid: 'profile71',
    favoritedby: 'profile20,profile3',
    labels: 'label38,label19',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate51',
    title: 'Romantic Evening Melodies',
    description: 'Funky disco classics that get the party started and keep you grooving.',
    creatorid: 'profile55',
    favoritedby: 'profile22,profile85,profile3',
    labels: 'label89,label143,label58,label188',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate52',
    title: 'Alternative Revival',
    description: 'Blissful lo-fi beats perfect for studying or relaxing with a book.',
    creatorid: 'profile20',
    favoritedby: 'profile67,profile83,profile3',
    labels: 'label103,label70,label92,label23,label158',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate53',
    title: 'Hip Hop Heatwave',
    description: 'Whimsical and playful tunes that ignite your childlike wonder.',
    creatorid: 'profile1',
    favoritedby: 'profile4,profile56,profile3',
    labels: 'label2,label119,label76,label40',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate54',
    title: 'Laid-Back Reggae',
    description: 'Heart-pounding heavy metal tracks that unleash your inner headbanger.',
    creatorid: 'profile39',
    favoritedby: 'profile3',
    labels: 'label99,label24,label75,label33',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate55',
    title: 'EDM Party Starters',
    description: 'Ethereal ambient sounds that create a serene and meditative atmosphere.',
    creatorid: 'profile92',
    favoritedby: 'profile53,profile3',
    labels: 'label13,label45,label109,label122,label31,label153',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate56',
    title: 'Blues Legends',
    description: 'Catchy reggaeton hits that will have you dancing in no time.',
    creatorid: 'profile12',
    favoritedby: 'profile76,profile31,profile3',
    labels: 'label176,label79,label114,label117',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate57',
    title: 'Indie Pop Parade',
    description: 'Timeless classic rock anthems that never go out of style.',
    creatorid: 'profile68',
    favoritedby: 'profile10,profile62,profile3',
    labels: 'label30,label165',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate58',
    title: 'Motown Memories',
    description: 'Cinematic scores that bring to life the emotions of the silver screen.',
    creatorid: 'profile71',
    favoritedby: 'profile43,profile17,profile3',
    labels: 'label41,label20,label65,label171',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate59',
    title: 'Sunset Serenade',
    description: "Nostalgic '90s hits that take you back to the golden era of music.",
    creatorid: 'profile45',
    favoritedby: 'profile34,profile63,profile3',
    labels: 'label199,label16,label25,label41',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate60',
    title: "Feel-Good '80s",
    description: 'Smooth and soulful neo-soul tracks that captivate with their silky vocals.',
    creatorid: 'profile42',
    favoritedby: 'profile39,profile3',
    labels: 'label68,label160,label29,label63',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate61',
    title: 'Classical Masterpieces',
    description: 'Introspective indie folk tunes that resonate with the human experience.',
    creatorid: 'profile23',
    favoritedby: 'profile3',
    labels: 'label151,label65,label128,label178,label22',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate62',
    title: 'Dancefloor Anthems',
    description: 'Dance-pop bops that will make you forget your worries and hit the dance floor.',
    creatorid: 'profile31',
    favoritedby: 'profile5,profile3',
    labels: 'label147,label194,label140',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate63',
    title: 'Country Heartbreak',
    description: 'Atmospheric trip-hop beats that create a hypnotic and introspective mood.',
    creatorid: 'profile38',
    favoritedby: 'profile88,profile20,profile3',
    labels: 'label151,label171,label54,label33,label161',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate64',
    title: 'Jazz Legends Live',
    description: 'Upbeat Latin hits that make you want to salsa the night away.',
    creatorid: 'profile54',
    favoritedby: 'profile3',
    labels: 'label44,label60',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate65',
    title: 'Rock Riot',
    description: 'Heartfelt country ballads that tell stories of love, loss, and resilience.',
    creatorid: 'profile51',
    favoritedby: 'profile8,profile68,profile3',
    labels: 'label127,label42,label38',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate66',
    title: 'Inspirational Beats',
    description: 'Energetic punk rock anthems that ignite your rebellious spirit.',
    creatorid: 'profile67',
    favoritedby: 'profile65,profile3',
    labels: 'label71,label11,label79,label185',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate67',
    title: 'Acoustic Covers',
    description: 'Captivating world fusion tracks that blend diverse musical traditions.',
    creatorid: 'profile48',
    favoritedby: 'profile57,profile3',
    labels: 'label66,label100,label98,label135,label13',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate68',
    title: 'Pop Divas',
    description: 'Sentimental and romantic R&B slow jams for cozy evenings with your loved one.',
    creatorid: 'profile91',
    favoritedby: 'profile41,profile63,profile3',
    labels: 'label140,label198,label162,label69,label86',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate69',
    title: 'Smooth Grooves',
    description: 'Progressive electronic sounds that push the boundaries of sonic experimentation.',
    creatorid: 'profile21',
    favoritedby: 'profile73,profile3',
    labels: 'label95,label59,label109,label69',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate70',
    title: 'Road Trip Memories',
    description: 'Raw and emotional grunge tracks that capture the angst of a generation.',
    creatorid: 'profile22',
    favoritedby: 'profile3',
    labels: 'label104,label166,label25',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate71',
    title: 'Latin Party Mix',
    description: 'Inspiring and uplifting pop-rock anthems that empower and motivate.',
    creatorid: 'profile19',
    favoritedby: 'profile28,profile3',
    labels: 'label3,label69,label96',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate72',
    title: 'Relaxing Nature Sounds',
    description: 'Atmospheric post-punk tracks that blend gloom with infectious melodies.',
    creatorid: 'profile57',
    favoritedby: 'profile4,profile3',
    labels: 'label94,label122,label69,label62',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate73',
    title: 'Indie Rock Rendezvous',
    description: 'Evocative soundscapes that transport you to ethereal and otherworldly realms.',
    creatorid: 'profile40',
    favoritedby: 'profile10,profile3',
    labels: 'label80,label107',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate74',
    title: 'Motivational Momentum',
    description: 'Hypnotic techno beats that transport you to a pulsating dancefloor.',
    creatorid: 'profile47',
    favoritedby: 'profile22,profile3',
    labels: 'label199,label31,label10',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate75',
    title: 'Funky Fresh',
    description: 'Passionate flamenco music that evokes the spirit and passion of Spain.',
    creatorid: 'profile23',
    favoritedby: 'profile88,profile39,profile3',
    labels: 'label176,label196,label89,label134',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate76',
    title: '2000s Flashback',
    description: 'Infectious indie pop-rock tunes perfect for road trips and summer adventures.',
    creatorid: 'profile14',
    favoritedby: 'profile4,profile3',
    labels: 'label80,label36',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate77',
    title: 'Tropical House Paradise',
    description: 'Ethereal and haunting folk songs that captivate with their delicate melodies.',
    creatorid: 'profile59',
    favoritedby: 'profile3',
    labels: 'label192,label88,label104,label89,label124,label70',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate78',
    title: 'Heartfelt Ballads',
    description: 'Irresistible K-pop hits that will have you singing in Korean in no time.',
    creatorid: 'profile77',
    favoritedby: 'profile3',
    labels: 'label201,label24,label37',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate79',
    title: 'Chillstep Journey',
    description: 'Hypnotic and entrancing psytrance beats that elevate your mind and body.',
    creatorid: 'profile50',
    favoritedby: 'profile72,profile3',
    labels: 'label64',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate80',
    title: 'Reggae Fusion',
    description: "Intimate and introspective singer-songwriter tracks that bare the artist's soul.",
    creatorid: 'profile1',
    favoritedby: 'profile39,profile3',
    labels: 'label38,label76,label73,label130,label10,label87,label164',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate81',
    title: 'Vintage Swing',
    description: 'Sizzling salsa rhythms that ignite your hips and bring the Latin groove to your ears.',
    creatorid: 'profile7',
    favoritedby: 'profile83,profile3',
    labels: 'label111',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate82',
    title: 'Hip Hop Hustle',
    description: 'Breezy and carefree surf rock tunes that transport you to sunny beaches.',
    creatorid: 'profile44',
    favoritedby: 'profile60,profile3',
    labels: 'label105,label55,label37,label120,label13',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate83',
    title: 'Instrumental Oasis',
    description: 'Atmospheric darkwave tracks that merge melancholy with electronic textures.',
    creatorid: 'profile85',
    favoritedby: 'profile59,profile3',
    labels: 'label80,label1,label64,label187',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate84',
    title: 'Classic Rock Rewind',
    description: 'Soulful and sultry jazz vocals that caress your ears and touch your heart.',
    creatorid: 'profile31',
    favoritedby: 'profile78,profile9,profile3',
    labels: 'label83,label3',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate85',
    title: 'Ambient Escapes',
    description: 'Anthems of self-empowerment and liberation to inspire and uplift.',
    creatorid: 'profile59',
    favoritedby: 'profile28,profile3',
    labels: 'label95,label110,label141,label150',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate86',
    title: 'Folk Fusions',
    description: "Nostalgic '80s hits that bring back memories of neon lights and big hair.",
    creatorid: 'profile11',
    favoritedby: 'profile6,profile3',
    labels: 'label67,label91,label70',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate87',
    title: 'Pop Perfection',
    description: 'Hypnotic ambient dub tracks that create a deep and immersive sonic experience.',
    creatorid: 'profile28',
    favoritedby: 'profile70,profile64,profile3',
    labels: 'label1,label155,label157,label81',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate88',
    title: 'Jazz Fusion Jam',
    description: 'Infectious African beats that will have you moving to the rhythm of the continent.',
    creatorid: 'profile2',
    favoritedby: 'profile3',
    labels: 'label121,label142',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate89',
    title: 'Alternative Anthems',
    description: 'Irresistibly catchy pop punk anthems that make you want to jump and shout.',
    creatorid: 'profile9',
    favoritedby: 'profile89,profile9,profile3',
    labels: 'label138,label137,label128,label39,label104,label113',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate90',
    title: 'Country Classics',
    description: 'Euphoric trance melodies that transport you to euphoric dancefloor moments.',
    creatorid: 'profile35',
    favoritedby: 'profile3',
    labels: 'label78,label107,label190,label28',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate91',
    title: 'Smooth R&B Rhythms',
    description: 'Reflective and introspective hip-hop tracks that delve into personal experiences.',
    creatorid: 'profile14',
    favoritedby: 'profile64,profile3',
    labels: 'label152,label111,label69,label150,label199',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate92',
    title: 'Cinematic Soundscapes',
    description: 'Dynamic and explosive post-hardcore songs that unleash raw emotion and energy.',
    creatorid: 'profile35',
    favoritedby: 'profile3',
    labels: 'label44,label199,label168,label8',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate93',
    title: 'Dance Hits Explosion',
    description: 'Atmospheric and haunting dark folk tunes that create an eerie and mystical atmosphere.',
    creatorid: 'profile33',
    favoritedby: 'profile66,profile3',
    labels: 'label23,label81,label36',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate94',
    title: 'Psychedelic Trip',
    description: 'Swooning and romantic bossa nova melodies that capture the essence of Brazil.',
    creatorid: 'profile60',
    favoritedby: 'profile8,profile3',
    labels: 'label70,label1,label190,label178,label25,label182,label194',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate95',
    title: 'Romantic Pop Gems',
    description: 'Captivating experimental pop tracks that defy conventions and push boundaries.',
    creatorid: 'profile82',
    favoritedby: 'profile53,profile56,profile28,profile3',
    labels: 'label40,label124,label50',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate96',
    title: 'Indie Electronica Ecstasy',
    description: "Dynamic and intricate math rock compositions that challenge the listener's expectations.",
    creatorid: 'profile20',
    favoritedby: 'profile18,profile3',
    labels: 'label117,label20,label109,label29',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate97',
    title: 'Motivational Mayhem',
    description: 'Nostalgic and heartfelt emo anthems that tap into the raw emotions of youth.',
    creatorid: 'profile22',
    favoritedby: 'profile78,profile3',
    labels: 'label100,label103,label121,label138',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate98',
    title: 'Bluesy Awakening',
    description: 'Melancholicfolktronica tracks that blend acoustic elements with electronic textures.',
    creatorid: 'profile30',
    favoritedby: 'profile33,profile3',
    labels: 'label148,label23,label192',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate99',
    title: 'Upbeat Ukulele Strumming',
    description: 'Hypnotic and entrancing Middle Eastern beats that transport you to ancient lands.',
    creatorid: 'profile65',
    favoritedby: 'profile84,profile3',
    labels: 'label176,label61,label22',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate100',
    title: 'Experimental Soundscapes',
    description: 'Whimsical and enchanting chamber pop songs that weave intricate musical tapestries.',
    creatorid: 'profile60',
    favoritedby: 'profile37,profile3',
    labels: 'label110,label35,label199,label4,label6,label146',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate101',
    title: 'Best of the 2000s',
    description: 'Melodic and introspective post-rock tracks that build and crescendo with emotion.',
    creatorid: 'profile86',
    favoritedby: 'profile16,profile62,profile3',
    labels: 'label2,label13,label159,label122,label119',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate102',
    title: 'Best of the 90s',
    description: 'Dynamic and soulful Afrobeat grooves that make you want to dance and celebrate life.',
    creatorid: 'profile47',
    favoritedby: 'profile8,profile91,profile3',
    labels: 'label2,label67,label51,label132,label167,label85,label127',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate103',
    title: 'Best of the 80s',
    description: 'Atmospheric and ethereal dream pop melodies that create a dreamy and introspective mood.',
    creatorid: 'profile30',
    favoritedby: 'profile7,profile3',
    labels: 'label2,label148,label19,label66',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate104',
    title: 'Best of the 70s',
    description: 'Nostalgic and heartwarming Americana tunes that evoke the spirit of the open road.',
    creatorid: 'profile12',
    favoritedby: 'profile18,profile13',
    labels: 'label2,label26,label94',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate105',
    title: 'Best of the 60s',
    description: 'Uplifting and empowering pop anthems that inspire confidence and self-belief.',
    creatorid: 'profile83',
    favoritedby: '',
    labels: 'label2,label58,label165,label88,label174,label146,label41,label3',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate106',
    title: 'Best of the 50s',
    description: 'Captivating and introspective ambient techno tracks that immerse you in a sonic journey.',
    creatorid: 'profile10',
    favoritedby: 'profile61,profile85,profile62,profile92',
    labels: 'label2,label35,label136,label82,label18',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate107',
    title: 'Best of the 2010s',
    description: 'Hypnotic and pulsating tribal house beats that transport you to the heart of the dancefloor.',
    creatorid: 'profile43',
    favoritedby: 'profile45,profile26',
    labels: 'label2,label174,label150,label176,label103,label140',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate108',
    title: 'Best of the 2020s',
    description: 'Soulful and groovy neo-soul tracks that fuse classic R&B with modern sensibilities.',
    creatorid: 'profile17',
    favoritedby: 'profile40',
    labels: 'label2,label94,label80,label23,label117',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate109',
    title: 'Best of January 2023',
    description: 'Anthemic and anthological post-punk revival songs that capture the essence of a generation.',
    creatorid: 'profile42',
    favoritedby: '',
    labels: 'label2,label91,label176,label173',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate110',
    title: 'Best of February 2023',
    description: 'Enigmatic and otherworldly dark ambient compositions that create a haunting sonic atmosphere.',
    creatorid: 'profile33',
    favoritedby: '',
    labels: 'label2,label202,label1,label196,label88,label128,label76',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate111',
    title: 'Best of March 2023',
    description: 'Smooth and sensual smooth jazz tunes that create an atmosphere of relaxation and romance.',
    creatorid: 'profile92',
    favoritedby: '',
    labels: 'label2,label22,label129,label8,label165,label93,label144,label198',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate112',
    title: 'Best of April 2023',
    description: 'Enchanting and ethereal neoclassical tracks that transport you to a world of beauty and serenity.',
    creatorid: 'profile53',
    favoritedby: 'profile89,profile51,profile60',
    labels: 'label2,label17,label124,label12',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate113',
    title: 'Best of May 2023',
    description: 'Dynamic and energetic future bass beats that blend electronic elements with melodic sensibilities.',
    creatorid: 'profile59',
    favoritedby: '',
    labels: 'label2,label7,label157',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate114',
    title: 'Best of June 2023',
    description: 'Uplifting and euphoric Eurodance hits that make you want to move your body to the rhythm.',
    creatorid: 'profile88',
    favoritedby: 'profile27',
    labels: 'label2,label52,label68,label79',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate115',
    title: 'Best of July 2023',
    description: 'Cinematic and epic instrumental post-rock tracks that evoke emotions and tell stories without words.',
    creatorid: 'profile40',
    favoritedby: 'profile50,profile64',
    labels: 'label2,label84,label153,label172,label70,label120,label143',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate116',
    title: 'Best of August 2023',
    description: 'Blissful and soothing lo-fi hip-hop beats that create a cozy and laid-back atmosphere.',
    creatorid: 'profile44',
    favoritedby: 'profile10,profile26,profile65',
    labels: 'label2,label164,label188',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate117',
    title: 'Best of September 2023',
    description: 'Passionate and heartfelt flamenco guitar compositions that evoke the fiery spirit of Spain.',
    creatorid: 'profile12',
    favoritedby: '',
    labels: 'label2,label187,label116',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate118',
    title: 'Best of October 2023',
    description: 'Hypnotic and introspective minimal techno beats that take you on a journey of deep introspection.',
    creatorid: 'profile46',
    favoritedby: 'profile46',
    labels: 'label2,label40,label132,label179',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate119',
    title: 'Best of November 2023',
    description: 'Reflective and introspective folk-pop songs that explore the complexities of love and life.',
    creatorid: 'profile33',
    favoritedby: 'profile50,profile51',
    labels: 'label2,label192',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate120',
    title: 'Best of December 2023',
    description: 'Infectious and feel-good indie dance tracks that combine catchy melodies with irresistible grooves.',
    creatorid: 'profile83',
    favoritedby: 'profile10',
    labels: 'label2,label115',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate121',
    title: 'Best of the 2000s',
    description:
      'Atmospheric and introspective darkwave tracks that blend electronic elements with gothic sensibilities.',
    creatorid: 'profile78',
    favoritedby: 'profile31',
    labels: 'label2,label78,label122',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate122',
    title: 'Best of the 90s',
    description: 'Smooth and soulful contemporary R&B tracks that showcase the power of vocal prowess.',
    creatorid: 'profile41',
    favoritedby: 'profile59',
    labels: 'label2,label179,label104,label53',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate123',
    title: 'Best of the 80s',
    description: 'Energetic and anthemic pop-rock hits that make you want to sing along at the top of your lungs.',
    creatorid: 'profile19',
    favoritedby: '',
    labels: 'label2,label13',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate124',
    title: 'Best of the 70s',
    description:
      'Atmospheric and immersive psybient tracks that create a transcendent and meditative sonic experience.',
    creatorid: 'profile78',
    favoritedby: '',
    labels: 'label2,label106,label169,label110,label54',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate125',
    title: 'Best of the 60s',
    description: 'Uplifting and empowering reggaeton hits that infuse infectious rhythms with empowering lyrics.',
    creatorid: 'profile43',
    favoritedby: 'profile72',
    labels: 'label2,label52,label83,label72,label138,label199',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate126',
    title: 'Best of the 50s',
    description: 'Dreamy and introspective bedroom pop melodies that capture the essence of teenage nostalgia.',
    creatorid: 'profile87',
    favoritedby: '',
    labels: 'label2,label174,label114',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate127',
    title: 'Best of the 2010s',
    description:
      'Dynamic and evocative art rock compositions that push the boundaries of conventional song structures.',
    creatorid: 'profile60',
    favoritedby: 'profile68,profile90',
    labels: 'label2,label81,label197,label24',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate128',
    title: 'Best of the 2020s',
    description: 'Soulful and evocative trip-hop tracks that blend elements of hip-hop, electronica, and soul.',
    creatorid: 'profile64',
    favoritedby: 'profile51',
    labels: 'label2,label171,label129,label106,label103,label67',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate129',
    title: 'Best of January 2023',
    description: 'Anthemic and empowering pop-punk anthems that capture the rebellious spirit of youth.',
    creatorid: 'profile70',
    favoritedby: '',
    labels: 'label2,label21',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate130',
    title: 'Best of February 2023',
    description: 'Ethereal and enchanting Celtic folk tunes that transport you to the magical landscapes of Ireland.',
    creatorid: 'profile16',
    favoritedby: 'profile47',
    labels: 'label2',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate131',
    title: 'Best of March 2023',
    description: 'Blissful and relaxing chillstep beats that create a serene and atmospheric sonic landscape.',
    creatorid: 'profile57',
    favoritedby: '',
    labels: 'label2,label183,label6',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate132',
    title: 'Best of April 2023',
    description: 'Dynamic and explosive metalcore tracks that combine aggressive riffs with melodic sensibilities.',
    creatorid: 'profile42',
    favoritedby: '',
    labels: 'label2,label139,label134,label121,label100,label67,label104',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate133',
    title: 'Best of May 2023',
    description: 'Moody and atmospheric synth-pop songs that transport you to a nostalgic and neon-lit world.',
    creatorid: 'profile86',
    favoritedby: '',
    labels: 'label2,label132,label200,label166,label10,label183',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate134',
    title: 'Best of June 2023',
    description:
      'Passionate and emotive indie folk ballads that tug at the heartstrings and tell stories of love and loss.',
    creatorid: 'profile20',
    favoritedby: 'profile53,profile56',
    labels: 'label2,label82,label154',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate135',
    title: 'Best of July 2023',
    description: 'Irresistibly catchy K-pop hits that showcase the infectious energy and talent of Korean idols.',
    creatorid: 'profile51',
    favoritedby: 'profile15,profile44',
    labels: 'label2,label189,label67,label32,label72',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate136',
    title: 'Best of August 2023',
    description:
      'Melancholic and introspective dark folk tracks that blend acoustic instrumentation with haunting lyrics.',
    creatorid: 'profile64',
    favoritedby: 'profile11',
    labels: 'label2,label32',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate137',
    title: 'Best of September 2023',
    description: 'Captivating and atmospheric witch house tracks that create a dark and enigmatic sonic atmosphere.',
    creatorid: 'profile27',
    favoritedby: 'profile66',
    labels: 'label2,label50,label121,label42,label25',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate138',
    title: 'Best of October 2023',
    description: 'Upbeat and infectious indie pop-rock anthems that capture the essence of youthful exuberance.',
    creatorid: 'profile53',
    favoritedby: '',
    labels: 'label2,label100,label171,label46',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate139',
    title: 'Best of November 2023',
    description:
      'Hypnotic and melodic progressive house beats that take you on a journey of euphoric dancefloor moments.',
    creatorid: 'profile13',
    favoritedby: '',
    labels: 'label2',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate140',
    title: 'Best of December 2023',
    description: 'Smooth and soulful smooth jazz tunes that create an atmosphere of relaxation and sophistication.',
    creatorid: 'profile29',
    favoritedby: 'profile34',
    labels: 'label2,label79,label5,label161',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate141',
    title: 'Best of the 2000s',
    description:
      'Reflective and introspective acoustic singer-songwriter tracks that tell stories of love, heartbreak, and self-discovery.',
    creatorid: 'profile84',
    favoritedby: 'profile57',
    labels: 'label2,label128,label180',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate142',
    title: 'Best of the 90s',
    description:
      "Energetic and anthemic garage rock tracks that capture the raw and rebellious spirit of rock 'n' roll.",
    creatorid: 'profile32',
    favoritedby: 'profile70',
    labels: 'label2,label115,label110,label190',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate143',
    title: 'Best of the 80s',
    description:
      'Dreamy and ethereal shoegaze melodies that envelop you in a wall of fuzzy guitars and hazy atmospheres.',
    creatorid: 'profile67',
    favoritedby: 'profile89',
    labels: 'label2,label144,label191,label46,label110',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate144',
    title: 'Best of the 70s',
    description:
      'Uplifting and euphoric EDM tracks that ignite the dancefloor with their infectious beats and soaring melodies.',
    creatorid: 'profile77',
    favoritedby: '',
    labels: 'label2,label79,label167',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate145',
    title: 'Best of the 60s',
    description:
      'Enigmatic and atmospheric dark ambient compositions that transport you to eerie and otherworldly realms.',
    creatorid: 'profile54',
    favoritedby: 'profile84',
    labels: 'label2,label47,label173',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate146',
    title: 'Best of the 50s',
    description:
      'Passionate and soulful blues-rock tracks that evoke the spirit of the Mississippi Delta and the greats who came before.',
    creatorid: 'profile62',
    favoritedby: '',
    labels: 'label2,label196,label29,label63,label69,label113',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate147',
    title: 'Best of the 2010s',
    description: 'Energetic beats to get your heart pumping and feet moving.',
    creatorid: 'profile25',
    favoritedby: 'profile11',
    labels: 'label2,label52,label8,label166',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate148',
    title: 'Best of the 2020s',
    description: 'Soothing melodies for relaxation and unwinding after a long day.',
    creatorid: 'profile83',
    favoritedby: 'profile23,profile71',
    labels: 'label2,label37,label151,label142,label4,label181',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate149',
    title: 'Best of January 2023',
    description: 'Upbeat and catchy tunes to brighten your mood and lift your spirits.',
    creatorid: 'profile3',
    favoritedby: 'profile81,profile36',
    labels: 'label2,label40,label122',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate150',
    title: 'Best of February 2023',
    description: 'Soulful ballads that touch the depths of your emotions.',
    creatorid: 'profile86',
    favoritedby: 'profile28,profile83',
    labels: 'label2,label84,label191,label77,label85,label3,label76',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate151',
    title: 'Best of March 2023',
    description: 'Feel-good anthems that will have you singing along at the top of your lungs.',
    creatorid: 'profile37',
    favoritedby: '',
    labels: 'label2,label44,label92',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate152',
    title: 'Best of April 2023',
    description: 'Atmospheric tracks that transport you to another world.',
    creatorid: 'profile65',
    favoritedby: 'profile4,profile35',
    labels: 'label2,label105,label128,label194',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate153',
    title: 'Best of May 2023',
    description: 'Epic orchestral compositions that evoke a sense of grandeur and adventure.',
    creatorid: 'profile15',
    favoritedby: 'profile21,profile28',
    labels: 'label2,label76,label150',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate154',
    title: 'Best of June 2023',
    description: 'Nostalgic hits that take you back to a different era.',
    creatorid: 'profile87',
    favoritedby: 'profile21,profile6',
    labels: 'label2,label97,label148,label112',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate155',
    title: 'Best of July 2023',
    description: 'Laid-back acoustic vibes for those lazy Sunday mornings.',
    creatorid: 'profile30',
    favoritedby: 'profile75,profile87',
    labels: 'label2',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate156',
    title: 'Best of August 2023',
    description: 'Dancefloor bangers that will make you move and groove all night long.',
    creatorid: 'profile33',
    favoritedby: '',
    labels: 'label2,label166,label35,label17,label42,label6',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate157',
    title: 'Best of September 2023',
    description: 'Soul-stirring love songs that tug at your heartstrings.',
    creatorid: 'profile24',
    favoritedby: 'profile66,profile60',
    labels: 'label2,label178',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate158',
    title: 'Best of October 2023',
    description: 'Inspirational tracks to motivate and empower you.',
    creatorid: 'profile72',
    favoritedby: '',
    labels: 'label2,label201,label149,label47,label1',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate159',
    title: 'Best of November 2023',
    description: 'Mind-bending electronic sounds that push the boundaries of music.',
    creatorid: 'profile29',
    favoritedby: 'profile34,profile17',
    labels: 'label2,label120,label170,label137,label67,label183',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate160',
    title: 'Best of December 2023',
    description: 'Heartfelt folk tunes that tell stories of life and love.',
    creatorid: 'profile79',
    favoritedby: '',
    labels: 'label2,label122,label192,label169',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate161',
    title: 'Best of the 2000s',
    description: 'Uplifting gospel music that fills your spirit with joy and hope.',
    creatorid: 'profile4',
    favoritedby: 'profile10,profile9',
    labels: 'label2,label162,label104',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate162',
    title: 'Best of the 90s',
    description: 'Intense rock anthems that make you want to unleash your inner rebel.',
    creatorid: 'profile46',
    favoritedby: 'profile75,profile14,profile70',
    labels: 'label2,label32,label61,label50,label96',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate163',
    title: 'Best of the 80s',
    description: 'Quirky and eclectic tracks that defy genre boundaries.',
    creatorid: 'profile89',
    favoritedby: 'profile57',
    labels: 'label2,label164,label89,label154,label13',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate164',
    title: 'Best of the 70s',
    description: 'Mellow jazz tunes perfect for a cozy evening with a glass of wine.',
    creatorid: 'profile16',
    favoritedby: '',
    labels: 'label2,label161,label152,label74,label21',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate165',
    title: 'Best of the 50s',
    description: 'Powerful rap verses that speak truth and challenge the status quo.',
    creatorid: 'profile42',
    favoritedby: 'profile67,profile11,profile7,profile76,profile64,profile36',
    labels: 'label2,label114,label74,label27',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate166',
    title: 'Best of the 2010s',
    description: 'Dreamy indie pop melodies that create an atmosphere of bliss.',
    creatorid: 'profile12',
    favoritedby: 'profile71,profile49',
    labels: 'label2,label25,label188,label113',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate167',
    title: 'Best of the 2020s',
    description: 'Melancholic songs that capture the beauty of sadness and longing.',
    creatorid: 'profile79',
    favoritedby: '',
    labels: 'label2,label17,label69,label111,label78,label178',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate168',
    title: 'Best of January 2023',
    description: 'Sensual R&B tracks that set the mood for a romantic evening.',
    creatorid: 'profile26',
    favoritedby: 'profile27,profile28',
    labels: 'label2,label138,label158,label136',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate169',
    title: 'Best of February 2023',
    description: 'Captivating classical compositions that stir your soul.',
    creatorid: 'profile4',
    favoritedby: 'profile21',
    labels: 'label2,label83',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate170',
    title: 'Best of March 2023',
    description: 'Reggae rhythms that bring the warmth of the Caribbean to your ears.',
    creatorid: 'profile53',
    favoritedby: 'profile24',
    labels: 'label2,label84,label25,label52',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate171',
    title: 'Best of April 2023',
    description: 'Dynamic instrumental tracks that ignite your imagination.',
    creatorid: 'profile87',
    favoritedby: '',
    labels: 'label2,label48,label36',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate172',
    title: 'Best of May 2023',
    description: 'Up-and-coming artists showcasing their raw talent and unique sound.',
    creatorid: 'profile38',
    favoritedby: 'profile40,profile76',
    labels: 'label2,label103,label30',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate173',
    title: 'Best of June 2023',
    description: 'Epic movie soundtracks that transport you into cinematic worlds.',
    creatorid: 'profile2',
    favoritedby: '',
    labels: 'label2,label175,label25,label29,label10,label36,label57',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate174',
    title: 'Best of July 2023',
    description: 'Up-tempo country hits that make you want to put on your cowboy boots.',
    creatorid: 'profile17',
    favoritedby: 'profile83,profile37',
    labels: 'label2,label45,label114,label93',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate175',
    title: 'Best of September 2023',
    description: 'Experimental sounds that challenge traditional notions of music.',
    creatorid: 'profile33',
    favoritedby: 'profile66,profile50',
    labels: 'label2,label20,label139,label82,label30,label149,label136,label92,label87',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate176',
    title: 'Best of October 2023',
    description: 'Chill electronic beats perfect for a laid-back evening with friends.',
    creatorid: 'profile65',
    favoritedby: '',
    labels: 'label2',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate177',
    title: 'Best of November 2023',
    description: 'Anthems of resilience and strength to help you overcome obstacles.',
    creatorid: 'profile28',
    favoritedby: '',
    labels: 'label2,label75,label67',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate178',
    title: 'Best of December 2023',
    description: 'Indie rock anthems for the rebels and dreamers.',
    creatorid: 'profile56',
    favoritedby: 'profile32',
    labels: 'label2,label24,label175,label178',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate179',
    title: 'Best of 2022',
    description: 'Melodic metal tracks that blend aggression with intricate harmonies.',
    creatorid: 'profile57',
    favoritedby: 'profile75,profile55',
    labels: 'label2,label153,label116,label31',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate180',
    title: 'Best of 2022',
    description: 'Inspirational gospel hymns that uplift and inspire.',
    creatorid: 'profile27',
    favoritedby: 'profile5,profile17',
    labels: 'label2,label39',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate181',
    title: 'Best of 2022',
    description: 'Bittersweet songs that capture the complexities of human emotions.',
    creatorid: 'profile26',
    favoritedby: '',
    labels: 'label2,label94,label122,label108',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate182',
    title: 'Best of 2022',
    description: 'Catchy pop hits that will have you singing along from the first note.',
    creatorid: 'profile78',
    favoritedby: 'profile10,profile73,profile75,profile84',
    labels: 'label2,label155,label7',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate183',
    title: 'Best of 2022',
    description: 'Soulful blues melodies that speak directly to your heart.',
    creatorid: 'profile29',
    favoritedby: 'profile63',
    labels: 'label2,label6,label130,label73,label173,label44',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate184',
    title: 'Best of 2022',
    description: 'Rhythmic hip-hop tracks that make you nod your head to the beat.',
    creatorid: 'profile41',
    favoritedby: 'profile39',
    labels: 'label2,label21,label31,label142',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate185',
    title: 'Best of 2020',
    description: 'Atmospheric post-rock compositions that build and swell with emotion.',
    creatorid: 'profile31',
    favoritedby: 'profile78',
    labels: 'label2,label39,label15',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate186',
    title: 'Best of 2020',
    description: 'Emotional piano ballads that tug at your heartstrings.',
    creatorid: 'profile23',
    favoritedby: '',
    labels: 'label2,label15',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate187',
    title: 'Best of 2020',
    description: 'Infectious world music rhythms that make you want to dance.',
    creatorid: 'profile82',
    favoritedby: 'profile70',
    labels: 'label2,label128,label38,label21',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate188',
    title: 'Best of 2021',
    description: "Raw and honest singer-songwriter tracks that lay bare the artist's soul.",
    creatorid: 'profile30',
    favoritedby: 'profile15',
    labels: 'label2,label173,label139,label45',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate189',
    title: 'Best of 2021',
    description: 'Groovy funk tunes that get your body moving and your hips shaking.',
    creatorid: 'profile45',
    favoritedby: '',
    labels: 'label2,label9,label190,label164,label151,label100',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate190',
    title: 'Best of 2021',
    description: 'Ambient electronic sounds that create a serene and introspective atmosphere.',
    creatorid: 'profile87',
    favoritedby: '',
    labels: 'label2,label130,label149,label67',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate191',
    title: 'Best of 2021',
    description: 'Enchanting Celtic melodies that transport you to mystical lands.',
    creatorid: 'profile88',
    favoritedby: '',
    labels: 'label2,label200',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate192',
    title: 'Best of 2021',
    description: 'Thought-provoking alternative tracks that challenge societal norms.',
    creatorid: 'profile54',
    favoritedby: 'profile58',
    labels: 'label2,label132,label155,label107,label202,label38,label30,label72',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate193',
    title: 'Best of 2021',
    description: 'Emotional orchestral arrangements that bring tears to your eyes.',
    creatorid: 'profile77',
    favoritedby: '',
    labels: 'label2,label81',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate194',
    title: 'New Music Friday - January 6, 2023',
    description: 'Joyful and lively folk songs that make you want to join in on the chorus.',
    creatorid: 'profile33',
    favoritedby: 'profile58,profile2',
    labels: 'label1',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate195',
    title: 'New Music Friday - February 17, 2023',
    description: 'Mind-bending progressive rock tracks that take you on a musical journey.',
    creatorid: 'profile11',
    favoritedby: 'profile42',
    labels: 'label1,label181',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate196',
    title: 'New Music Friday - March 24, 2023',
    description: 'Lush and dreamy shoegaze sounds that envelop you in a sonic haze.',
    creatorid: 'profile7',
    favoritedby: 'profile85',
    labels: 'label1,label79,label114,label145,label200',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate197',
    title: 'New Music Friday - April 7, 2023',
    description: 'Funky disco classics that get the party started and keep you grooving.',
    creatorid: 'profile20',
    favoritedby: '',
    labels: 'label1,label10',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate198',
    title: 'New Music Friday - May 19, 2023',
    description: 'Blissful lo-fi beats perfect for studying or relaxing with a book.',
    creatorid: 'profile71',
    favoritedby: 'profile4',
    labels: 'label1,label108,label183,label121',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate199',
    title: 'New Music Friday - June 2, 2023',
    description: 'Whimsical and playful tunes that ignite your childlike wonder.',
    creatorid: 'profile71',
    favoritedby: 'profile33',
    labels: 'label1,label38,label162,label81,label149,label91,label116,label51,label121',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate200',
    title: 'New Music Friday - July 7, 2023',
    description: 'Heart-pounding heavy metal tracks that unleash your inner headbanger.',
    creatorid: 'profile81',
    favoritedby: 'profile78',
    labels: 'label1,label184,label107',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate201',
    title: 'New Music Friday - August 11, 2023',
    description: 'Ethereal ambient sounds that create a serene and meditative atmosphere.',
    creatorid: 'profile39',
    favoritedby: 'profile23,profile16,profile8',
    labels: 'label1,label192,label88',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate202',
    title: 'New Music Friday - September 15, 2023',
    description: 'Catchy reggaeton hits that will have you dancing in no time.',
    creatorid: 'profile1',
    favoritedby: '',
    labels: 'label1,label182',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate203',
    title: 'New Music Friday - October 20, 2023',
    description: 'Timeless classic rock anthems that never go out of style.',
    creatorid: 'profile73',
    favoritedby: 'profile24,profile6',
    labels: 'label1,label93,label52,label144,label156',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate204',
    title: 'New Music Friday - November 3, 2023',
    description: 'Cinematic scores that bring to life the emotions of the silver screen.',
    creatorid: 'profile36',
    favoritedby: 'profile56,profile33',
    labels: 'label1,label15,label107,label159',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate205',
    title: 'New Music Friday - December 8, 2023',
    description: "Nostalgic '90s hits that take you back to the golden era of music.",
    creatorid: 'profile80',
    favoritedby: 'profile34',
    labels: 'label1,label139,label9,label149',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate206',
    title: 'New Music Friday - January 13, 2023',
    description: 'Smooth and soulful neo-soul tracks that captivate with their silky vocals.',
    creatorid: 'profile59',
    favoritedby: 'profile10,profile54,profile11',
    labels: 'label1,label115,label63,label136,label23,label176,label51,label106,label56,label32',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate207',
    title: 'New Music Friday - February 24, 2023',
    description: 'Introspective indie folk tunes that resonate with the human experience.',
    creatorid: 'profile7',
    favoritedby: 'profile29',
    labels: 'label1,label54,label64',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate208',
    title: 'New Music Friday - March 31, 2023',
    description: 'Dance-pop bops that will make you forget your worries and hit the dance floor.',
    creatorid: 'profile3',
    favoritedby: 'profile8',
    labels: 'label1,label130,label58,label39',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate209',
    title: 'New Music Friday - April 14, 2023',
    description: 'Atmospheric trip-hop beats that create a hypnotic and introspective mood.',
    creatorid: 'profile27',
    favoritedby: '',
    labels: 'label1,label183,label148,label12',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate210',
    title: 'New Music Friday - May 26, 2023',
    description: 'Upbeat Latin hits that make you want to salsa the night away.',
    creatorid: 'profile65',
    favoritedby: 'profile73,profile21,profile28,profile72',
    labels: 'label1,label123,label38,label143',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate211',
    title: 'New Music Friday - June 9, 2023',
    description: 'Heartfelt country ballads that tell stories of love, loss, and resilience.',
    creatorid: 'profile40',
    favoritedby: 'profile64',
    labels: 'label1,label154,label64,label199,label96',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate212',
    title: 'New Music Friday - July 14, 2023',
    description: 'Energetic punk rock anthems that ignite your rebellious spirit.',
    creatorid: 'profile70',
    favoritedby: 'profile34,profile28',
    labels: 'label1,label65,label131,label129,label82,label149',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate213',
    title: 'New Music Friday - August 18, 2023',
    description: 'Captivating world fusion tracks that blend diverse musical traditions.',
    creatorid: 'profile92',
    favoritedby: 'profile78',
    labels: 'label1,label68,label201,label63,label13',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate214',
    title: 'New Music Friday - September 22, 2023',
    description: 'Sentimental and romantic R&B slow jams for cozy evenings with your loved one.',
    creatorid: 'profile73',
    favoritedby: 'profile39',
    labels: 'label1',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate215',
    title: 'New Music Friday - October 27, 2023',
    description: 'Progressive electronic sounds that push the boundaries of sonic experimentation.',
    creatorid: 'profile61',
    favoritedby: 'profile35,profile20,profile79',
    labels: 'label1,label122,label163,label93,label129',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate216',
    title: 'New Music Friday - November 10, 2023',
    description: 'Raw and emotional grunge tracks that capture the angst of a generation.',
    creatorid: 'profile55',
    favoritedby: 'profile73,profile25,profile60',
    labels: 'label1,label153,label51,label20,label160',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate217',
    title: 'New Music Friday - December 15, 2023',
    description: 'Inspiring and uplifting pop-rock anthems that empower and motivate.',
    creatorid: 'profile26',
    favoritedby: 'profile34,profile20,profile79',
    labels: 'label1,label160,label26',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate218',
    title: 'New Music Friday - January 20, 2023',
    description: 'Atmospheric post-punk tracks that blend gloom with infectious melodies.',
    creatorid: 'profile39',
    favoritedby: 'profile67,profile40,profile27',
    labels: 'label1,label171,label123',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate219',
    title: 'Best of the Decade',
    description: 'Evocative soundscapes that transport you to ethereal and otherworldly realms.',
    creatorid: 'profile3',
    favoritedby: 'profile31',
    labels: 'label2,label132',
    isranked: true,
    undefined: '',
  },
  {
    id: 'crate220',
    title: 'Melancholic Mornings',
    description: 'Hypnotic techno beats that transport you to a pulsating dancefloor.',
    creatorid: 'profile43',
    favoritedby: 'profile34,profile7',
    labels: 'label109,label191,label71,label169',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate221',
    title: 'Pumped Up Anthems',
    description: 'Passionate flamenco music that evokes the spirit and passion of Spain.',
    creatorid: 'profile65',
    favoritedby: 'profile14,profile92',
    labels: 'label60,label185,label188,label23,label179',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate222',
    title: 'Indie Delights',
    description: 'Infectious indie pop-rock tunes perfect for road trips and summer adventures.',
    creatorid: 'profile42',
    favoritedby: 'profile20',
    labels: 'label173,label76,label100,label103',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate223',
    title: 'Throwback Jams',
    description: 'Ethereal and haunting folk songs that captivate with their delicate melodies.',
    creatorid: 'profile5',
    favoritedby: 'profile47',
    labels: 'label40,label192,label93',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate224',
    title: 'Chill Vibes Only',
    description: 'Irresistible K-pop hits that will have you singing in Korean in no time.',
    creatorid: 'profile60',
    favoritedby: '',
    labels: 'label3,label154,label56,label31',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate225',
    title: 'Ultimate Road Trip Hits',
    description: 'Hypnotic and entrancing psytrance beats that elevate your mind and body.',
    creatorid: 'profile44',
    favoritedby: 'profile36',
    labels: 'label163',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate226',
    title: 'Electro Pop Bangers',
    description: "Intimate and introspective singer-songwriter tracks that bare the artist's soul.",
    creatorid: 'profile32',
    favoritedby: 'profile77',
    labels: 'label145,label115,label132,label135,label34,label122,label147',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate227',
    title: 'Soulful Serenade',
    description: 'Sizzling salsa rhythms that ignite your hips and bring the Latin groove to your ears.',
    creatorid: 'profile47',
    favoritedby: 'profile81',
    labels: 'label195,label52,label172,label19',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate228',
    title: 'Fresh Discoveries',
    description: 'Breezy and carefree surf rock tunes that transport you to sunny beaches.',
    creatorid: 'profile12',
    favoritedby: 'profile10,profile49,profile44,profile21',
    labels: 'label57,label121,label72',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate229',
    title: 'Rock Classics Rewind',
    description: 'Atmospheric darkwave tracks that merge melancholy with electronic textures.',
    creatorid: 'profile56',
    favoritedby: 'profile53,profile11',
    labels: 'label29,label72,label116,label183,label202',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate230',
    title: 'EDM Explosion',
    description: 'Soulful and sultry jazz vocals that caress your ears and touch your heart.',
    creatorid: 'profile39',
    favoritedby: '',
    labels: 'label62,label171,label164,label128,label115',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate231',
    title: 'Smooth Jazz Retreat',
    description: 'Anthems of self-empowerment and liberation to inspire and uplift.',
    creatorid: 'profile30',
    favoritedby: '',
    labels: 'label192,label12,label114',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate232',
    title: 'Rap Royalty',
    description: "Nostalgic '80s hits that bring back memories of neon lights and big hair.",
    creatorid: 'profile67',
    favoritedby: 'profile39,profile37',
    labels: 'label198,label194',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate233',
    title: 'Acoustic Affair',
    description: 'Hypnotic ambient dub tracks that create a deep and immersive sonic experience.',
    creatorid: 'profile15',
    favoritedby: '',
    labels: 'label29,label21,label57,label76',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate234',
    title: 'Dance Party Anthems',
    description: 'Infectious African beats that will have you moving to the rhythm of the continent.',
    creatorid: 'profile34',
    favoritedby: '',
    labels: 'label14,label192',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate235',
    title: 'Golden Oldies',
    description: 'Irresistibly catchy pop punk anthems that make you want to jump and shout.',
    creatorid: 'profile21',
    favoritedby: 'profile68',
    labels: 'label86,label116,label59,label29',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate236',
    title: 'Alternative Rock Riot',
    description: 'Euphoric trance melodies that transport you to euphoric dancefloor moments.',
    creatorid: 'profile75',
    favoritedby: 'profile61,profile35',
    labels: 'label143,label44,label140,label30,label127',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate237',
    title: 'Country Roads Collection',
    description: 'Reflective and introspective hip-hop tracks that delve into personal experiences.',
    creatorid: 'profile79',
    favoritedby: 'profile76,profile48,profile65,profile37',
    labels: 'label39,label126,label73,label170,label168',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate238',
    title: 'Rhythm & Blues Revival',
    description: 'Dynamic and explosive post-hardcore songs that unleash raw emotion and energy.',
    creatorid: 'profile19',
    favoritedby: '',
    labels: 'label167,label56,label199',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate239',
    title: 'Workout Warriors',
    description: 'Atmospheric and haunting dark folk tunes that create an eerie and mystical atmosphere.',
    creatorid: 'profile39',
    favoritedby: 'profile65',
    labels: 'label66,label152,label176',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate240',
    title: 'Songs for Rainy Days',
    description: 'Swooning and romantic bossa nova melodies that capture the essence of Brazil.',
    creatorid: 'profile83',
    favoritedby: 'profile38,profile1,profile84',
    labels: 'label52,label199,label51,label65,label57,label7',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate241',
    title: 'Reggae Rhythms',
    description: 'Captivating experimental pop tracks that defy conventions and push boundaries.',
    creatorid: 'profile25',
    favoritedby: 'profile19',
    labels: 'label167,label51,label53',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate242',
    title: '90s Nostalgia',
    description: "Dynamic and intricate math rock compositions that challenge the listener's expectations.",
    creatorid: 'profile10',
    favoritedby: 'profile6',
    labels: 'label51,label126,label184,label5,label134',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate243',
    title: 'Summer Grooves',
    description: 'Nostalgic and heartfelt emo anthems that tap into the raw emotions of youth.',
    creatorid: 'profile86',
    favoritedby: 'profile66',
    labels: 'label164,label45',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate244',
    title: 'Road Trip Mixtape',
    description: 'Melancholicfolktronica tracks that blend acoustic elements with electronic textures.',
    creatorid: 'profile92',
    favoritedby: 'profile52',
    labels: 'label26,label127,label3',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate245',
    title: 'Latin Fever',
    description: 'Hypnotic and entrancing Middle Eastern beats that transport you to ancient lands.',
    creatorid: 'profile78',
    favoritedby: 'profile50',
    labels: 'label196,label104,label125,label145,label148',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate246',
    title: 'Relaxing Instrumentals',
    description: 'Whimsical and enchanting chamber pop songs that weave intricate musical tapestries.',
    creatorid: 'profile82',
    favoritedby: '',
    labels: 'label183,label7,label125,label64',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate247',
    title: 'Feel-Good Favorites',
    description: 'Melodic and introspective post-rock tracks that build and crescendo with emotion.',
    creatorid: 'profile68',
    favoritedby: 'profile9,profile31',
    labels: 'label98,label154,label27,label175,label48,label97',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate248',
    title: 'Electronic Escapade',
    description: 'Dynamic and soulful Afrobeat grooves that make you want to dance and celebrate life.',
    creatorid: 'profile86',
    favoritedby: '',
    labels: 'label66,label76,label100,label186,label202',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate249',
    title: 'Rock Ballad Bliss',
    description: 'Atmospheric and ethereal dream pop melodies that create a dreamy and introspective mood.',
    creatorid: 'profile56',
    favoritedby: '',
    labels: 'label117,label27,label56',
    isranked: false,
    undefined: '',
  },
  {
    id: 'crate250',
    title: 'Soul Sisters',
    description: 'Nostalgic and heartwarming Americana tunes that evoke the spirit of the open road.',
    creatorid: 'profile27',
    favoritedby: 'profile69',
    labels: 'label59,label170,label22',
    isranked: false,
    undefined: '',
  },
];
