export const userSeedArray = [
  {
    id: 'user1',
    email: 'ricechrisdtreat@email.com',
    emailverified: false,
    role: 'ADMIN',
    profiles: 'user1',
    hname: 'Chris Rice',
  },
  {
    id: 'user2',
    email: 'mls636@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user2',
    hname: 'Morgan Sendor',
  },
  {
    id: 'user3',
    email: 'afantano@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user3',
    hname: 'Anthony Fantano',
  },
  {
    id: 'user4',
    email: 'yelyahwilliams@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user4',
    hname: 'Hayley Williams',
  },
  {
    id: 'user5',
    email: 'cristiano@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user5',
    hname: 'Cristiano Ronaldo',
  },
  {
    id: 'user6',
    email: 'selenagomez@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user6',
    hname: 'Selena Gomez',
  },
  {
    id: 'user7',
    email: 'kyliejenner@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user7',
    hname: 'Kylie Jenner',
  },
  {
    id: 'user8',
    email: 'leomessi@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user8',
    hname: 'Lionel Messi',
  },
  {
    id: 'user9',
    email: 'therock@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user9',
    hname: 'The Rock',
  },
  {
    id: 'user10',
    email: 'arianagrande@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user10',
    hname: 'Ariana Grande',
  },
  {
    id: 'user11',
    email: 'kimkardashian@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user11',
    hname: 'Kim Kardashian',
  },
  {
    id: 'user12',
    email: 'beyonce@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user12',
    hname: 'Beyonce',
  },
  {
    id: 'user13',
    email: 'khloekardashian@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user13',
    hname: 'Khloe Kardashian',
  },
  {
    id: 'user14',
    email: 'jlo@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user14',
    hname: 'Jennifer Lopez',
  },
  {
    id: 'user15',
    email: 'mileycyrus@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user15',
    hname: 'Miley Cyrus',
  },
  {
    id: 'user16',
    email: 'kourtneykardash@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user16',
    hname: 'Kourtney Kardashian',
  },
  {
    id: 'user17',
    email: 'taylorswift@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user17',
    hname: 'Taylor Swift',
  },
  {
    id: 'user18',
    email: 'justinbieber@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user18',
    hname: 'Justin Bieber',
  },
  {
    id: 'user19',
    email: 'kendalljenner@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user19',
    hname: 'Kendall Jenner',
  },
  {
    id: 'user20',
    email: 'neymarjr@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user20',
    hname: 'Neymar Jr',
  },
  {
    id: 'user21',
    email: 'nickiminaj@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user21',
    hname: 'Nicki Minaj',
  },
  {
    id: 'user22',
    email: 'billieeilish@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user22',
    hname: 'Billie Eilish',
  },
  {
    id: 'user23',
    email: 'iamcardib@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user23',
    hname: 'Cardi B',
  },
  {
    id: 'user24',
    email: 'kingjames@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user24',
    hname: 'LeBron James',
  },
  {
    id: 'user25',
    email: 'theellenshow@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user25',
    hname: 'Ellen DeGeneres',
  },
  {
    id: 'user26',
    email: 'katyperry@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user26',
    hname: 'Katy Perry',
  },
  {
    id: 'user27',
    email: 'kevinhart4real@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user27',
    hname: 'Kevin Hart',
  },
  {
    id: 'user28',
    email: 'badgalriri@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user28',
    hname: 'Rihanna',
  },
  {
    id: 'user29',
    email: 'zendaya@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user29',
    hname: 'Zendaya',
  },
  {
    id: 'user30',
    email: 'ddlovato@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user30',
    hname: 'Demi Lovato',
  },
  {
    id: 'user31',
    email: 'willsmith@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user31',
    hname: 'Will Smith',
  },
  {
    id: 'user32',
    email: 'shakira@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user32',
    hname: 'Shakira',
  },
  {
    id: 'user33',
    email: 'vindiesel@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user33',
    hname: 'Vin Diesel',
  },
  {
    id: 'user34',
    email: 'champagnepapi@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user34',
    hname: 'Drake',
  },
  {
    id: 'user35',
    email: 'justintimberlake@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user35',
    hname: 'Justin Timberlake',
  },
  {
    id: 'user36',
    email: 'usher@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user36',
    hname: 'Usher',
  },
  {
    id: 'user37',
    email: 'zayn@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user37',
    hname: 'Zayn Malik',
  },
  {
    id: 'user38',
    email: 'brunomars@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user38',
    hname: 'Bruno Mars',
  },
  {
    id: 'user39',
    email: 'eminem@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user39',
    hname: 'Eminem',
  },
  {
    id: 'user40',
    email: 'gigihadid@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user40',
    hname: 'Gigi Hadid',
  },
  {
    id: 'user41',
    email: 'caradelevingne@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user41',
    hname: 'Cara Delevingne',
  },
  {
    id: 'user42',
    email: 'zacefron@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user42',
    hname: 'Zac Efron',
  },
  {
    id: 'user43',
    email: 'adele@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user43',
    hname: 'Adele',
  },
  {
    id: 'user44',
    email: 'niallhoran@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user44',
    hname: 'Niall Horan',
  },
  {
    id: 'user45',
    email: 'teddysphotos@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user45',
    hname: 'Ed Sheeran',
  },
  {
    id: 'user46',
    email: 'snoopdogg@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user46',
    hname: 'Snoop Dogg',
  },
  {
    id: 'user47',
    email: 'davidbeckham@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user47',
    hname: 'David Beckham',
  },
  {
    id: 'user48',
    email: 'robertdowneyjr@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user48',
    hname: 'Robert Downey Jr.',
  },
  {
    id: 'user49',
    email: 'louist91@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user49',
    hname: 'Louis Tomlinson',
  },
  {
    id: 'user50',
    email: 'thehughjackman@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user50',
    hname: 'Hugh Jackman',
  },
  {
    id: 'user51',
    email: 'liampayne@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user51',
    hname: 'Liam Payne',
  },
  {
    id: 'user52',
    email: 'shawnmendes@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user52',
    hname: 'Shawn Mendes',
  },
  {
    id: 'user53',
    email: 'chrishemsworth@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user53',
    hname: 'Chris Hemsworth',
  },
  {
    id: 'user54',
    email: 'charlieputh@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user54',
    hname: 'Charlie Puth',
  },
  {
    id: 'user55',
    email: 'gal_gadot@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user55',
    hname: 'Gal Gadot',
  },
  {
    id: 'user56',
    email: 'prideofgypsies@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user56',
    hname: 'Jason Momoa',
  },
  {
    id: 'user57',
    email: 'dualipa@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user57',
    hname: 'Dua Lipa',
  },
  {
    id: 'user58',
    email: 'prattprattpratt@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user58',
    hname: 'Chris Pratt',
  },
  {
    id: 'user59',
    email: 'tomholland2013@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user59',
    hname: 'Tom Holland',
  },
  {
    id: 'user60',
    email: 'michaelbjordan@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user60',
    hname: 'Michael B. Jordan',
  },
  {
    id: 'user61',
    email: 'chrisevans@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user61',
    hname: 'Chris Evans',
  },
  {
    id: 'user62',
    email: 'markruffalo@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user62',
    hname: 'Mark Ruffalo',
  },
  {
    id: 'user63',
    email: 'scarlett.johansson.fc@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user63',
    hname: 'Scarlett Johansson',
  },
  {
    id: 'user64',
    email: 'twhiddleston@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user64',
    hname: 'Tom Hiddleston',
  },
  {
    id: 'user65',
    email: 'imsebastianstan@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user65',
    hname: 'Sebastian Stan',
  },
  {
    id: 'user66',
    email: 'anthonymackie@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user66',
    hname: 'Anthony Mackie',
  },
  {
    id: 'user67',
    email: 'elizabetholsenofficial@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user67',
    hname: 'Elizabeth Olsen',
  },
  {
    id: 'user68',
    email: 'paulruddofficial@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user68',
    hname: 'Paul Rudd',
  },
  {
    id: 'user69',
    email: 'jeremyrenner@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user69',
    hname: 'Jeremy Renner',
  },
  {
    id: 'user70',
    email: 'samuelljackson@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user70',
    hname: 'Samuel L. Jackson',
  },
  {
    id: 'user71',
    email: 'cobiesmulders@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user71',
    hname: 'Cobie Smulders',
  },
  {
    id: 'user72',
    email: 'zoesaldana@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user72',
    hname: 'Zoe Saldana',
  },
  {
    id: 'user73',
    email: 'bradleycooper_official@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user73',
    hname: 'Bradley Cooper',
  },
  {
    id: 'user74',
    email: 'vindiesel@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user74',
    hname: 'Vin Diesel',
  },
  {
    id: 'user75',
    email: 'davebautista@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user75',
    hname: 'Dave Bautista',
  },
  {
    id: 'user76',
    email: 'pom.klementieff@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user76',
    hname: 'Pom Klementieff',
  },
  {
    id: 'user77',
    email: 'karengillan@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user77',
    hname: 'Karen Gillan',
  },
  {
    id: 'user78',
    email: 'doncheadle@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user78',
    hname: 'Don Cheadle',
  },
  {
    id: 'user79',
    email: 'paulbettany@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user79',
    hname: 'Paul Bettany',
  },
  {
    id: 'user80',
    email: 'joshbrolin@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user80',
    hname: 'Josh Brolin',
  },
  {
    id: 'user81',
    email: 'brielarson@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user81',
    hname: 'Brie Larson',
  },
  {
    id: 'user82',
    email: 'benedictcum@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user82',
    hname: 'Benedict Cumberbatch',
  },
  {
    id: 'user83',
    email: 'tomhardy@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user83',
    hname: 'Tom Hardy',
  },
  {
    id: 'user84',
    email: 'vancityreynolds@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user84',
    hname: 'Ryan Reynolds',
  },
  {
    id: 'user85',
    email: 'jakegyllenhaal@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user85',
    hname: 'Jake Gyllenhaal',
  },
  {
    id: 'user86',
    email: 'margotrobbie@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user86',
    hname: 'Margot Robbie',
  },
  {
    id: 'user87',
    email: 'ryangosling@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user87',
    hname: 'Ryan Gosling',
  },
  {
    id: 'user88',
    email: 'annehathaway@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user88',
    hname: 'Anne Hathaway',
  },
  {
    id: 'user89',
    email: 'dwyanewade@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user89',
    hname: 'Dwayne Wade',
  },
  {
    id: 'user90',
    email: 'serenawilliams@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user90',
    hname: 'Serena Williams',
  },
  {
    id: 'user91',
    email: 'usainbolt@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user91',
    hname: 'Usain Bolt',
  },
  {
    id: 'user92',
    email: 'rogerfederer@email.com',
    emailverified: false,
    role: 'USER',
    profiles: 'user92',
    hname: 'Roger Federer',
  },
];
